### PR TITLE
operator kiali (1.82.0)

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
`[github-add-summary-comment : gather-info] 2024/04/16 01:11:07 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/home/nonroot": unable to create destination directory: mkdir /home/nonroot: permission denied`

That's nothing to do with my operator.  Going to restart the tests.

**Comment by iblancasa** [comment]
> `[github-add-summary-comment : gather-info] 2024/04/16 01:11:07 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/home/nonroot": unable to create destination directory: mkdir /home/nonroot: permission denied`
> 
> That's nothing to do with my operator. Going to restart the tests.

It seems the test is flaky or something. It fails for all the PRs.

**Pull request merged**
