### PR TITLE
operators postgresql (4.7.5)

### PR DESCRIPTION
**Pull request by tjmoore4**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [] Have you tested your Operator with all Custom Resource Definitions?
* [] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by J0zi** [comment]
@tjmoore4 se couple similar errors: `Field spec.preserveUnknownFields, Value 0xc00049b449: spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead` [here](https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/6085564049?check_suite_focus=true#step:6:1308)

**Comment by tjmoore4** [comment]
> @tjmoore4 see couple similar errors: `Field spec.preserveUnknownFields, Value 0xc00049b449: spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead` [here](https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/6085564049?check_suite_focus=true#step:6:1308). After fixing, check if `kiwi` test passed. Logs are included in the test itself.
> 
> Invalid CRD schema, unable to load/parse CRD into an object.

@J0zi I understand those errors to be related to operator-sdk using the 1.23 k8s library blocking the bundle validation. As this version is targeted to k8s 1.21 and below, I think this is being incorrectly flagged. I will also note that we're not explicitly setting `spec.preserveUnknownFields`, but the check is picking up the default value. Would there be any way to validate this bundle using an earlier version of operator-sdk for validation?

(We appear to be hitting the same thing in the [community operators repo](https://github.com/k8s-operatorhub/community-operators/pull/955).)

**Comment by camilamacedo86** [comment]
@tjmoore4, 

>@J0zi I understand those errors to be related to operator-sdk using the 1.23 k8s library blocking the bundle validation. As this version is targeted to k8s 1.21 and below, I think this is being incorrectly flagged. I will also note that we're not explicitly setting spec.preserveUnknownFields, but the check is picking up the default value. Would there be any way to validate this bundle using an earlier version of operator-sdk for validation?

Please, see: https://github.com/k8s-operatorhub/community-operators/pull/955#issuecomment-1106617472

This statement ` I understand those errors to be related to operator-sdk using the 1.23 k8s library` is not accurate.

**Comment by camilamacedo86** [comment]
@tjmoore4 , 

To fix this issue use `preserveUnknownFields: false` in your CRDs, eg: https://github.com/k8s-operatorhub/community-operators/pull/1108/files

**Comment by acornett21** [comment]
> @tjmoore4 ,
> 
> To fix this issue use `preserveUnknownFields: false` in your CRDs, eg: https://github.com/k8s-operatorhub/community-operators/pull/1108/files

@camilamacedo86 I commented on the other issue, adding this does not actually make this pass. We already tried that and re-ran these PR's and they still failed. This operator is already in the `certified` catalog and the `marketplace` catalog, which means they are able to properly run in the cluster they are targeted for ie a k8's `1.21` and not any version higher.  Since this operator is already in the catalog in clusters, why can't this be merged?

**Comment by camilamacedo86** [comment]
Hi @tjmoore4 , @J0zi @mvalarh, 

We open the issue https://github.com/operator-framework/operator-sdk/issues/5688 to analyse this case.
all tests are passing (less this one) and they are saying that all is working. So, I am ok with this PR getting merged. I think we need to understand more of the scenario and etc before jumping to any conclusion but shows that we have no reason to block their distribution.

**Pull request merged**
