### PR TITLE
operator loki-operator (0.6.0)

### PR DESCRIPTION
**Pull request by grafanabot**
Release loki-operator `0.6.0`.

cc @periklis @xperimental @JoaoBraveCoding @btaani @shwetaap

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Review by periklis — APPROVED** [review]

**Review by periklis — APPROVED** [review]
/lgtm

**Review by periklis — APPROVED** [review]
/ok-to-test

**Review by frzifus — APPROVED** [review]

**Review by IshwarKanse — APPROVED** [review]

**Comment by tomasbakk** [comment]
@periklis Hi. I noticed that you tried to restart the hosted pipeline. Assuming everything is alright here, can I merge the PR?

**Comment by IshwarKanse** [comment]
@tomasbakk We were checking if the bot auto-merges the commit when community-hosted-pipeline is passed. We noticed that we also need to add the grafanabot, which will open the commit, to the ci.yaml to get the auto-merge working. https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4266 However it seems we cannot retrigger the pipeline once its successful. :)

**Comment by periklis** [comment]
@tomasbakk Yes you can merge this if adding #4266 is not having an effect here yet but on the next release

**Comment by tomasbakk** [comment]
@IshwarKanse If you need to test something by running the hosted pipeline again, I can re-trigger it for you.

**Comment by IshwarKanse** [comment]
@tomasbakk Thanks, yeah that would be helpful, please help to retrigger. We'll be able to check if the auto-merge works or if it needs any other changes.

**Comment by IshwarKanse** [comment]
@tomasbakk The bot is still complaining 'Author of the PR is not listed as one of the reviewers in ci.yaml.' I think we can merge this one out and check with the next PR that will be opened.

**Pull request merged**
