### PR TITLE
operator camel-k (2.1.0)

### PR DESCRIPTION
**Pull request by squakez**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by squakez** [comment]
cc @oscerd @claudio4j @christophd

**Review by oscerd — APPROVED** [review]

**Comment by claudio4j** [comment]
The error in the log is 
```
time="2023-10-24T11:31:40Z" level=fatal msg="Failed to run bundle: create catalog: error creating registry pod: error building registry pod definition: configMap error: error updating ConfigMap: error creating ConfigMap: ConfigMap \"camel-k-catalog-configmap-partition-2\" is invalid: []: Too long: must have at most 1048576 bytes\n"
```

The log says operator-sdk is v1.28.0, and there is an issue "[run bundle - ConfigMap is invalid: []: Too long: must have at most 1048576 bytes](https://github.com/operator-framework/operator-sdk/issues/6323)" which was [fixed in 1.29](https://github.com/operator-framework/operator-sdk/releases/tag/v1.29.0).

We have to update the operator to 1.29 at least.

**Comment by claudio4j** [comment]
I wonder if the operator-sdk version is set somewhere else besides the annotation. I see there are different versions mentioned in the log `operator_sdk: v1.30.0` and `Installing quay.io/openshift-community-operators/camel-k:v2.0.1 with operator-sdk version: "v1.26.1",...`

**Comment by squakez** [comment]
I think the problem is on an upgrade test. Basically, it is trying to install previous version (2.0.1) which was released with an sdk (1.26) which suffer from the bug mentioned above. However, we cannot really do much more about it as that version was released already. IMO we can get past this and merge anyhow.

**Comment by mporrato** [comment]
@squakez I've updated the ci to use the latest operator-sdk version. Can you rebase this PR to pick up the change?

**Comment by squakez** [comment]
@mporrato can this be merged? Not really sure what the error is this time. It seems different than previous failures.

**Comment by mporrato** [comment]
@squakez have you tried actually running the bundle on ocp 4.10?
I see a bunch of messages like
```
    - time="2023-11-16T10:39:28Z" level=info msg="requirements were not met" csv=camel-k-operator.v2.1.0 id=HV8re namespace=testupgrade phase=Pending
    - time="2023-11-16T10:39:28Z" level=info msg="couldn't ensure RBAC in target namespaces" csv=camel-k-operator.v2.1.0 error="no owned roles found" id=z3gk8 namespace=testupgrade phase=Pending
    - 'E1116 10:39:28.793885       1 queueinformer_operator.go:290] sync {"update" "testupgrade/camel-k-operator.v2.1.0"} failed: no owned roles found'
    - time="2023-11-16T10:39:28Z" level=info msg="requirements were not met" csv=camel-k-operator.v2.1.0 id=8iePk namespace=testupgrade phase=Pending
    - time="2023-11-16T10:39:29Z" level=info msg="couldn't ensure RBAC in target namespaces" csv=camel-k-operator.v2.1.0 error="no owned roles found" id=SlrKE namespace=testupgrade phase=Pending
    - 'E1116 10:39:29.043938       1 queueinformer_operator.go:290] sync {"update" "testupgrade/camel-k-operator.v2.1.0"} failed: no owned roles found'
```
Since 4.10 is officially EOL, an option would be to start adding `com.redhat.openshift.versions=v4.11` to annotations.yaml to the bundles from now on, if you don't care about ocp 4.10 and earlier.

**Pull request merged**
