### PR TITLE
operator kiali (1.69.0)

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Can someone tell me what is going wrong here and how this can be fixed? This looks unrelated to anything that has to do with my operator:

```
TASK [bundle_validation_filter : Set fact] *************************************
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'bvf_label' is undefined. 'bvf_label' is undefined
  
    The error appears to be in '/home/runner/.ansible/pull/fv-az1028-527.atwrdzpjfxuexoqyq1q1ta0xqe.cx.internal.cloudapp.net/upstream/roles/bundle_validation_filter/tasks/generate_label.yml': line 94, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: "Set fact"
      ^ here
```

**Comment by jmazzitelli** [comment]
round and round we go...

/retest-required

**Comment by jmazzitelli** [comment]
i give up.

**Comment by jmazzitelli** [comment]
@haripate @mporrato any ideas what is going on with this PR?

**Comment by haripate** [comment]
> @haripate @mporrato any ideas what is going on with this PR?

Looking into the issue.

**Comment by jmazzitelli** [comment]
>failed: could not watch pod: the pod ci-op-ym98xntv/deploy-operator-on-openshift-deploy-operator failed after 19m26s (failed containers: test): ContainerFailed one or more containers exited

I will assume this is more CI related failures, since that pod `ci-op-ym98xntv/deploy-operator-on-openshift-deploy-operator` is not related to the operator being published in this PR.

**Pull request merged**
