### PR TITLE
operators [N] [CI] shipwright-operator (0.9.0)

### PR DESCRIPTION
**Pull request by adambkaplan**
Add Shipwright Operator to the Red Hat Community operators. This will
let OpenShift users install Shipwright. Installing Shipwright will also
install OpenShift Pipelines if it has not been installed already.

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by adambkaplan** [comment]
@jozzi @mvalarh Deploys on OpenShift fail with the following:

```
Failed to run bundle: pull bundle image: error pulling image quay.io/openshift-community-operators/shipwright-operator:v0.9.0
```

Is there a chicken/egg problem here? Does someone need to make the shipwright-operator images public on quay?

**Comment by J0zi** [comment]
@adambkaplan  if you check https://operatorhub.io/preview with your CSV,  There is the field Created at  on the right panel. Please fill it in your CSV.

**Comment by J0zi** [comment]
@adambkaplan are you able to install your operator on OCP v4.6? Pipeline is not able to do so.

**Comment by adambkaplan** [comment]
@J0zi upstream actually requires k8s 1.21 or higher, updating the min kube version here.

**Comment by J0zi** [comment]
@adambkaplan min kube is for k8s and it should be aligned with openshift label. So please add  `com.redhat.openshift.versions: v4.8` to `annotations.yaml`

**Comment by adambkaplan** [comment]
@J0zi kiwi / Full operator test failed with the following, no other errors appear in the test:

```
TASK [validate_operator_bundle : Add errors to file '/tmp/operator-test/operator-files/operator_sdk_bundle_validate_warnings_and_errors.txt'] ***
fatal: [localhost]: FAILED! => 
  msg: 'Invalid data passed to ''loop'', it requires a list, got this instead: . Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup.'

PLAY RECAP *********************************************************************
localhost                  : ok=132  changed=31   unreachable=0    failed=1    skipped=142  rescued=0    ignored=0   
```

**Comment by mvalarh** [comment]
> @J0zi kiwi / Full operator test failed with the following, no other errors appear in the test:
> 
> ```
> TASK [validate_operator_bundle : Add errors to file '/tmp/operator-test/operator-files/operator_sdk_bundle_validate_warnings_and_errors.txt'] ***
> fatal: [localhost]: FAILED! => 
>   msg: 'Invalid data passed to ''loop'', it requires a list, got this instead: . Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup.'
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=132  changed=31   unreachable=0    failed=1    skipped=142  rescued=0    ignored=0   
> ```

This is fixed now

**Pull request merged**
