### PR TITLE
operators [CI] project-quay

### PR DESCRIPTION
**Pull request by HammerMeetNail**
* Updates Quay reviewer names to match Github usernames

### CODE REVIEW

**Comment by J0zi** [comment]
> @bdettelb,@hdonnay,@jcroslan,@kwestpha,@rmarasch,@sleesinc,@sdadi,@fmissi,@obulatov,@syahmed,@hgovinda,@BCaton,@joking,@doconnor , please approve as you are original reviewer(s).
> 
> * To add more contributors to `ci.yaml` follow instruction [here](https://operator-framework.github.io/community-operators/operator-ci-yaml).
> * To approve follow instruction [here](https://redhat-openshift-ecosystem.github.io/community-operators-prod/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator)

@HammerMeetNail could you please get an approval from one ^ of your colleagues?

**Review by harishsurf — APPROVED** [review]
lgtm

**Review by hdonnay — APPROVED** [review]

**Comment by HammerMeetNail** [comment]
@J0zi Done, team has approved. How long does it take for this to get merged?

**Comment by mvalarh** [comment]
> @J0zi Done, team has approved. How long does it take for this to get merged?

After reviewer approved it, author could do `/unhold`

**Pull request merged**
