### PR TITLE
operator [O] kiali (1.47.0)

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@mporrato @haripate Everything is green here, not sure why it didn't automatically merge. Can someone tell me how to merge this?

**Comment by jmazzitelli** [comment]
I submitted a github issue to document the problem that this PR is not auto-merging when it looks like it should: https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/3262

**Comment by mporrato** [comment]
@jmazzitelli it didn't automatically merge because non-trivial updates to existing bundles are not supposed to be automatically merged.
I don't think this change is needed because the bundle specified in the replaces field is not required to exist.

**Comment by jmazzitelli** [comment]
> @jmazzitelli it didn't automatically merge because non-trivial updates to existing bundles are not supposed to be automatically merged. I don't think this change is needed because the bundle specified in the replaces field is not required to exist.

@mporrato I think this change is needed.

Let me explain what happened. I removed old/obsolete versions of kiali - everything older than 1.47. I did this on OperatorHub.io in [this PR](https://github.com/k8s-operatorhub/community-operators/pull/3202) and the Red Hat community catalog in [this PR](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3246).

When I removed those old versions, I forgot to remove the "replaces" field in the 1.47 CSV. When I did this change over in the OperatorHub.io repo, that completely broke kiali on OperatorHub.io - it completely removed kiali from OperatorHub.io (this link produced a 404 at that time: https://operatorhub.io/operator/kiali).

To fix that, I had to remove the "replaces" field in 1.47 CSV (I did that in [this PR](https://github.com/k8s-operatorhub/community-operators/pull/3208)). Now OperatorHub.io correctly shows  Kiali as you see at https://operatorhub.io/operator/kiali

Notice that [PR](https://github.com/k8s-operatorhub/community-operators/pull/3208) that introduced the fix for kiali on OperatorHub.io is the same change I'm doing here in this PR, this is done in order to fix the Red Hat community catalog.

In addition, I would like the CSVs to be as identical as possible across the [k8s repo here](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/kiali) and the [Red Hat catalog here](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/kiali) so that's another reason this PR is needed.

**Pull request merged**
