### PR TITLE
operators kubeturbo (8.3.0)

### PR DESCRIPTION
**Pull request by esara**
Signed-off-by: esara <endre.sara@turbonomic.com>

### CODE REVIEW

**Review by enlinxu — APPROVED** [review]

**Comment by J0zi** [comment]
@esara, please fix metadata.annotations.containerImage. It should be exactly the same as the operator image.

**Comment by esara** [comment]
> @esara, please fix metadata.annotations.containerImage. It should be exactly the same as the operator image.

sorry about the typo - it fixed now

**Pull request merged**
