### PR TITLE
operator apicurio-api-controller (0.0.1)

### PR DESCRIPTION
**Pull request by jsenko**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/contributing-prerequisites/)?
* [x] Are you familiar with our [operator pipeline](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/pipelines_overview/)?
* [x] Have you tested your Operator with all Custom Resource Definitions [packaging](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/contributing-prerequisites/#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Your submission should not

* [x] Add more than one operator bundle per PR
* [x] Modify any operator
* [x] Rename an operator
* [x] Modify any files outside the above-mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human-readable name and 1-liner description about your Operator
* [x] Valid [category](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories) name <sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by jsenko** [comment]
I'm looking into the events API warning, but can someone explain the last two please: 
- How do I configure the validator
- How do I configure the file-based catalog? Do I just need to switch 
  ```
  fbc:
    enabled: true
  ```
  are there any compatibility risks? We need to support K8s 1.25+ and OCP 4.12+

**Comment by jsenko** [comment]
The operator should support both versions of `events.k8s.io` https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5581/files#diff-f3ca93ef28d7073cffcb535ccfcfe33420114e3a4d160f0e0469e8392bcc5977R105 Am I missing something?

**Comment by mantomas** [comment]
> Are there any compatibility risks? We need to support K8s 1.25+ and OCP 4.12+

@jsenko In this repository you can start directly with FBC as described [in the docs](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/fbc_workflow/), however there is no plan to support FBC in k8s repository, so you would need to maintain two different workflows.

**Comment by jsenko** [comment]
Isn't the catalog built by the pipelines here? Is there a difference in the bundle structure from our (authors of the operator) point of view? Thanks for help!

**Comment by mantomas** [comment]
The catalog itself is build by the pipeline here in both cases, but only the FBC gives you more control over the process (update/change/remove.. bundle versions etc.). Bundle structure is the same. You can check operators onboarded to FBC in `/catalogs`  and their corresponding `/operators/...` directories.

**Comment by jsenko** [comment]
Thank you, since that would take some time to set up as you said, we'll stay with the current setup and consider migrating in the future.

**Pull request merged**
