### PR TITLE
operator namespace-configuration-operator (1.2.5)

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
### New Submissions
* [ ] Has you operator [nested directory structure](https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#create-a-bundle)?
* [ ] Have you selected the Project *Community Operator Submissions* in your PR on the right-hand menu bar?
* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#sign-your-work)?
### Updates to existing Operators
* [x] Is your new CSV pointing to the previous version with the `replaces` property?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#bundle-format) defined in the `package.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#sign-your-work)?
### Your submission should not
* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Submit operators to both `upstream-community-operators` and `community-operators` at once
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**
### Operator Description must contain (in order)
1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator
### Operator Metadata should contain
* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo
Remember that you can preview your CSV [here](https://operatorhub.io/preview).
--
<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file a PR against this repo and explain your need
<sup>2</sup> For more information see [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.svg)

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
@Allda can you help me with this error? there seems to be something wrong with the system.

**Comment by mporrato** [comment]
@raffaelespazzoli looks like the operator keeps failing:
```
     Events:
      Type     Reason          Age                   From               Message
      ----     ------          ----                  ----               -------
      Normal   Scheduled       15m                   default-scheduler  Successfully assigned namespace-configuration-operator/namespace-configuration-operator-controller-manager-78f764bvvnd to ip-10-0-231-66.us-east-2.compute.internal
      Normal   AddedInterface  14m                   multus             Add eth0 [10.128.2.17/23] from openshift-sdn
      Normal   Pulling         14m                   kubelet            Pulling image "quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47"
      Normal   Pulled          14m                   kubelet            Successfully pulled image "quay.io/redhat-cop/kube-rbac-proxy@sha256:c68135620167c41e3d9f6c1d2ca1eb8fa24312b86186d09b8010656b9d25fb47" in 3.191201398s (3.191222549s including waiting)
      Normal   Created         14m                   kubelet            Created container kube-rbac-proxy
      Normal   Started         14m                   kubelet            Started container kube-rbac-proxy
      Normal   Pulled          14m (x4 over 14m)     kubelet            Container image "quay.io/redhat-cop/namespace-configuration-operator@sha256:20debaa7b91aebf034a0bd2baa80d37bac2b23be5c76efc2a6edbc14f942b2b1" already present on machine
      Normal   Created         14m (x4 over 14m)     kubelet            Created container manager
      Normal   Started         14m (x4 over 14m)     kubelet            Started container manager
      Warning  BackOff         4m47s (x54 over 14m)  kubelet            Back-off restarting failed container
```

**Comment by acornett21** [comment]
hi @raffaelespazzoli it looks like there is an issue with the controller pod please see below
```
oc logs -f -n namespace-configuration-operator namespace-configuration-operator-controller-manager-64f86769477 manager
/manager: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /manager)
/manager: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /manager)
```

and 
```
podman run -it --rm quay.io/redhat-cop/namespace-configuration-operator@sha256:20debaa7b91aebf034a0bd2baa80d37bac2b23be5c76efc2a6edbc14f942b2b1 /bin/bash
Trying to pull quay.io/redhat-cop/namespace-configuration-operator@sha256:20debaa7b91aebf034a0bd2baa80d37bac2b23be5c76efc2a6edbc14f942b2b1...
Getting image source signatures
Copying blob sha256:2882e4fed776240fa7a9273223618b3a1ac65807b1c1a62f8e8f4847225a9ce3
Copying blob sha256:dc35b837139a95d1b9f7f7b0435a024a74ab972416bdc248f3f608c9f917a753
Copying config sha256:91415312ebaa9383e1ea2822e48be8234a73e0083915b189acbad6dba523fc96
Writing manifest to image destination
/manager: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /manager)
/manager: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /manager)
```

so it looks like the controller image is not being built properly based on the go dependencies that are being used. If the controller does not need glibc you can add `CGO_ENABLED=0` when building the binary.

**Pull request merged**
