### PR TITLE
DELETE Eunomia Operator

### PR DESCRIPTION
**Pull request by akashkumar1982**
Eunomia Project has been Archived and this project is no longer maintained.

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Review by vinny-sabatini — APPROVED** [review]
Looks good to me
CC: @seanmalloy

**Review by seanmalloy — APPROVED** [review]

**Comment by vinny-sabatini** [comment]
Related to https://github.com/k8s-operatorhub/community-operators/pull/909

**Comment by vinny-sabatini** [comment]
Hi @J0zi and @mvalarh we are trying to remove the "Eunomia" operator from OperatorHub and from the OperatorHub catalog on OpenShift 4 as we have decided to archive the project.

We believe it looks like the `Operator test / PR-traffic-light` test is failing because we are removing the entire operator directory, which is resulting in `op_info` being an empty array, which then can not have the `keys` extracted from it in the role `operator_info_load` because there are none.

If you have any guidance as to a step we may be missing to cleanup this operator, it would be greatly appreciated!

**Comment by vinny-sabatini** [comment]
Hello again @J0zi and @mvalarh ! After some investigating, we believe we understand why this error is happening:
- The default for `op_info` is an empty list. Ref [Role operator_info, task main.yml, line 65](https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/upstream-community-dev/upstream/roles/operator_info/tasks/main.yml#L65)
- While checking the versions for an operator, the variable changes to a dictionary, however, this only happens if there is at least one version of the operator present. In our case, there are no versions because we are deleting the operator. Ref [Role operator_info, task op_info.yml, line 208](https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/upstream-community-dev/upstream/roles/operator_info/tasks/op_info.yml#L207-L208)
- Finally, the `oi_check_operator_info_keys` variable is defined using the keys from the variable `op_info`, however, since that is an array, it does not have the attribute `keys`, and the job fails. Ref [Role operator_info_load, task op_info_consistency.yml, Line 15](https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/upstream-community-dev/upstream/roles/operator_info_load/tasks/op_info_consistency.yml#L15)

I can attempt to submit a PR to fix this if you would like, however, I do not know what branches this would need to apply to. It looks like currently, this specific CI check uses the `upstream-community-dev` branch.

**Pull request merged**
