### PR TITLE
operator cert-manager (1.14.1-rc1)

### PR DESCRIPTION
**Pull request by wallrj**
Signed-off-by: Richard Wall <richard.wall@venafi.com>

### CODE REVIEW

**Comment by wallrj** [comment]
@Allda Can you help me understand how to fix failed `operator/test` check?

```yaml
        "errors": [
            {
                "name": "DeployableByOLM",
                "elapsed_time": 251130,
                "description": "Checking if the operator could be deployed by OLM",
                "help": "It is required that your operator could be deployed by OLM"
            }
        ],
```
-- https://gist.github.com/rh-operator-bundle-bot/aca8f1384f5ddf0b97443910c0efe69f#file-preflight-stdout-L29


> time="2024-02-07T15:16:40Z" level=info msg="check completed" check=DeployableByOLM err="error: watch: could not retrieve the object cert-manager-target/cert-manager.v1.13.3: failed to fetch the csv cert-manager.v1.13.3 from namespace cert-manager-target: could not retrieve csv: cert-manager-target/cert-manager.v1.13.3: client rate limiter Wait returned an error: context deadline exceeded" result=ERROR

-- https://gist.github.com/rh-operator-bundle-bot/aca8f1384f5ddf0b97443910c0efe69f#file-preflight-stderr-L998

**Comment by wallrj** [comment]
@Allda @mporrato Please help me get this merged. The preflight-test seems to have failed again:

> time="2024-02-07T16:27:05Z" level=info msg="check completed" check=DeployableByOLM err="error: watch: could not retrieve the object default/cert-manager.v1.13.3: failed to fetch the csv cert-manager.v1.13.3 from namespace default: could not retrieve csv: default/cert-manager.v1.13.3: client rate limiter Wait returned an error: context deadline exceeded" result=ERROR

https://gist.github.com/rh-operator-bundle-bot/8ff65b790cc4acdcb51033c0f59f2303#file-preflight-log-L966

And `evaluate-preflight-result` also seems to have failed:

> [github-add-summary-comment : gather-info] + PR_NAME=community-hosted-pipeline-runrl88q
> [github-add-summary-comment : gather-info] + mkdir community-hosted-pipeline-runrl88q
> [github-add-summary-comment : gather-info] + echo 'Getting pipeline logs'
> [github-add-summary-comment : gather-info] Getting pipeline logs
> [github-add-summary-comment : gather-info] + tkn pipelinerun logs community-hosted-pipeline-runrl88q
> [github-add-summary-comment : gather-info] task evaluate-preflight-result has failed: "step-evaluate-results" exited with code 1 (image: "quay.io/redhat-isv/operator-pipelines-images@sha256:3d480019e92aa6c51ab6625b6b14ff3af780f5cab9411add6a25d996897d3d83"); for logs run: kubectl -n operator-pipeline-prod logs community-hosted-pipeline-r87994dbd11a134e4ee94c2bb928a044f-pod -c step-evaluate-results
> [github-add-summary-comment : gather-info] 
> [github-add-summary-comment : gather-info] failed to get logs for task evaluate-preflight-result : container step-evaluate-results has failed  : [{"key":"test_result","value":"failure","type":1},{"key":"StartedAt","value":"2024-02-07T16:35:40.781Z","type":3}]

https://gist.github.com/rh-operator-bundle-bot/ec98c19258d4ae9239c0a9fa6b783acb#file-community-hosted-pipeline-runrl88q-log-L558

Is there something wrong with my new cert-manager v1.14.1-rc1 bundle?
or is there something about the previous bundle `v1.13.3` which is breaking these new pipeline scripts?

Thanks in advance for any help you can give.

**Comment by Allda** [comment]
@wallrj The test that is failing can't install the operator bundle on the cluster. I will try to reproduce it locally later this week on my cluster to see what's wrong with the operator. The issue should not be related to the previous bundle. I'll let you know if I find anything.

**Comment by wallrj** [comment]
> @wallrj The test that is failing can't install the operator bundle on the cluster. I will try to reproduce it locally later this week on my cluster to see what's wrong with the operator. The issue should not be related to the previous bundle. I'll let you know if I find anything.

Thanks @Allda 

Could the problem be related to the channels and default channel value that I use? 
For example, 

* cert-manager 1.13.3 
https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/6c5959b386ccbceece3796fd7e414f118ce769bd/operators/cert-manager/1.13.3/metadata/annotations.yaml#L6-L9
* cert-manager 1.14.1-rc1
https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/376251405018c5bd21b626141df92768f6563e4d/operators/cert-manager/1.14.1-rc1/metadata/annotations.yaml#L6-L8

**Pull request merged**
