### PR TITLE
operator project-quay (3.9.0-nightly.20230202)

### PR DESCRIPTION
**Pull request by quay-devel**
Add 3.9.0-nightly.20230202 to community operators

### CODE REVIEW

**Comment by J0zi** [comment]
@quay-devel  seems like the issue with naming was still not fixed. Too many dots in semver.

**Comment by J0zi** [comment]
@quay-devel There are too many dots in semver.

**Comment by dmage** [comment]
@J0zi what are constraints for version strings? It is a valid semver string, can we have `3.9.0-nightly.20230131`?

**Comment by dmage** [comment]
oh, I found the error: `unable to parse CSV quay-operator.clusterserviceversion.yaml: error unmarshaling JSON: while decoding JSON: Numeric PreRelease version must not contain leading zeroes \"01\", no bundle csv found, unable to load bundle from directory 3.9.0-nightly.2023.01.31/manifests`

**Pull request merged**
