### PR TITLE
operator [N] [CI] observability-operator (0.0.22)

### PR DESCRIPTION
**Pull request by sthaha**
This PR ships 0.0.22 version of observability-Operator. observability-operator provides the ability to create multiple monitoring-stacks on OpenShift without conflicting with the in-cluster monitoring.

Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by sthaha** [comment]
@mporrato Thank you for helping out. Do you know of the job is flaky or is there a genuine reason for the deployment on 4.10 fail while it passes on all other versions? 

```
TASK [Parse the operator bundle image, manifest and metadata] ******************

TASK [parse_operator_bundle : Inspect the bundle image with skopeo] ************
fatal: [localhost]: FAILED! => changed=true 
  cmd: skopeo inspect docker://quay.io/operator_testing/observability-operator:fdff9aba
  delta: '0:00:00.157287'
  end: '2023-05-30 03:08:49.987018'
  msg: non-zero return code
  rc: 1
  start: '2023-05-30 03:08:49.829731'
  stderr: 'time="2023-05-30T03:08:49Z" level=fatal msg="Error parsing image name \"docker://quay.io/operator_testing/observability-operator:fdff9aba\": reading manifest fdff9aba in quay.io/operator_testing/observability-operator: unknown: Tag fdff9aba was deleted or has expired. To pull, revive via time machine"'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by sthaha** [comment]
@mporrato @haripate , since this is my first submission, could you please advice if this PR need any further updates?

**Comment by sthaha** [comment]
@mporrato @haripate , Could you please help clarify if the failure on 4.14 is legit? 
 
From the [Prow Job ](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/2712/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.14-deploy-operator-on-openshift/1667355997825404928#1:build-log.txt%3A1553) I see that it  tries to `oc run <operator-image>` and fails due to missing `securityContext.*` and hence the question 


```
TASK [check_image_availability : Run external operator image 'quay.io/rhobs/observability-operator:0.0.22' on Openshift] ***
fatal: [localhost]: FAILED! => changed=true 
  cmd: /tmp/oc-SGJMesolu8ugEjmMmcyg/bin/oc run testimagepull --image=quay.io/rhobs/observability-operator:0.0.22 -n testimagepull
  delta: '0:00:00.444085'
  end: '2023-06-10 03:03:18.124541'
  msg: non-zero return code
  rc: 1
  start: '2023-06-10 03:03:17.680456'
push_pin
  stderr: 'Error from server (Forbidden): pods "testimagepull" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "testimagepull" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "testimagepull" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "testimagepull" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "testimagepull" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
TASK [check_image_availability : Print err message on Openshift] ***************
fatal: [localhost]: FAILED! => changed=false 
```

**Comment by mporrato** [comment]
@sthaha don't worry about the 4.14 tests: we are preparing the test infrastructure for the next openshift release: it won't prevent this PR from merging.

Please add the link to github source repo to the `.metadata.annotations.repository` field in the CSV file. All the rest looks ok.

**Comment by sthaha** [comment]
>@sthaha don't worry about the 4.14 tests: we are preparing the test infrastructure for the next openshift release: it won't prevent this PR from merging.

Thank you ! 

> Please add the link to github source repo to the .metadata.annotations.repository field in the CSV file. All the rest looks ok.

Thanks for pointer 🙇‍♂️. I have added and hopefully everything looks ok now 🤞

**Comment by sthaha** [comment]
@mporrato are we good to merge this?

**Comment by sthaha** [comment]
@mporrato Thank you for merging the operator.
Should this release https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/5315881606 contain the operator?  The [Release Process Doc](https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-release-process/#for-an-openshift-case-community-operators) seems a bit dated.

**Pull request merged**
