### PR TITLE
operator apicurio-registry (1.1.1-v2.5.9.final)

### PR DESCRIPTION
**Pull request by jsenko**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-via-pr.md)?
* [x] Are you familiar with our [operator pipeline](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/community-operator-pipeline.md)?
* [x] Have you tested your Operator with all Custom Resource Definitions [packaging](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md)?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/operator-ci-yaml.md##Operator-versioning)?
* [x] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#operator-icon) set?

### Your submission should not

* [x] Add more than one operator bundle per PR
* [x] Modify any operator
* [x] Rename an operator
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by jsenko** [comment]
I've added cluster version information. These `Warning: Value apicurio-registry-operator.v1.1.1-v2.5.9.final: this bundle is using APIs which were deprecated and removed in v1.25.` are OK, the operator detects which PDB version is available and uses the correct one for compatibility reasons.

**Comment by Allda** [comment]
@jsenko This is the same failure as seen in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4087#issuecomment-1993792167

```
('apicurio-registry-operator', '1.1.0-v2.4.12.final'), ('apicurio-registry-operator', '1.0.0-v2.0.0.final'), ('apicurio-registry', '0.0.3-v1.2.3.final'), ('apicurio-registry', '0.0.4-v1.3.2.final'), ('apicurio-registry', '0.0.1')
```

We have the same option here. Let me know which option you prefer.

**Comment by jsenko** [comment]
@Allda Thank you for the response. I'd prefer an exception for now, I'll consider the other options for the next major version of the operator.

**Comment by jsenko** [comment]
hi @Allda could you please point me in the right direction about how to debug these errors? Could `#1` and `#2` be caused by the operator name problem, i.e. `apicurio-registry/apicurio-registry` should be `apicurio-registry/apicurio-registry-operator`? Are image tags allowed or does the operator need to use hash as `#3` suggests?

`#1`

```
time="2024-03-13T10:10:09Z" level=trace msg="current subscription status" status="{\"catalogHealth\":[{\"catalogSourceRef\":{\"kind\":\"CatalogSource\",\"namespace\":\"apicurio-registry\",\"name\":\"apicurio-registry\",\"uid\":\"d50a35d7-c0fe-4b57-9fa9-c8deb6cf558e\",\"apiVersion\":\"operators.coreos.com/v1alpha1\",\"resourceVersion\":\"53808\"},\"lastUpdated\":\"2024-03-13T10:08:09Z\",\"healthy\":true},{\"catalogSourceRef\":{\"kind\":\"CatalogSource\",\"namespace\":\"openshift-marketplace\",\"name\":\"certified-operators\",\"uid\":\"0bb22ebf-e1aa-4080-965c-c314fbd0d594\",\"apiVersion\":\"operators.coreos.com/v1alpha1\",\"resourceVersion\":\"53194\"},\"lastUpdated\":\"2024-03-13T10:08:09Z\",\"healthy\":true},{\"catalogSourceRef\":{\"kind\":\"CatalogSource\",\"namespace\":\"openshift-marketplace\",\"name\":\"community-operators\",\"uid\":\"b5c91ad6-4a61-46bb-8d42-9b8da7549108\",\"apiVersion\":\"operators.coreos.com/v1alpha1\",\"resourceVersion\":\"53607\"},\"lastUpdated\":\"2024-03-13T10:08:09Z\",\"healthy\":true},{\"catalogSourceRef\":{\"kind\":\"CatalogSource\",\"namespace\":\"openshift-marketplace\",\"name\":\"redhat-marketplace\",\"uid\":\"065ad69f-7fd2-42a7-8598-49fbe4b6e9b9\",\"apiVersion\":\"operators.coreos.com/v1alpha1\",\"resourceVersion\":\"51863\"},\"lastUpdated\":\"2024-03-13T10:08:09Z\",\"healthy\":true},{\"catalogSourceRef\":{\"kind\":\"CatalogSource\",\"namespace\":\"openshift-marketplace\",\"name\":\"redhat-operators\",\"uid\":\"f684aad6-526a-4731-8b83-fcc55809fafc\",\"apiVersion\":\"operators.coreos.com/v1alpha1\",\"resourceVersion\":\"52539\"},\"lastUpdated\":\"2024-03-13T10:08:09Z\",\"healthy\":true}],\"conditions\":[{\"type\":\"ResolutionFailed\",\"status\":\"True\",\"reason\":\"ErrorPreventedResolution\",\"message\":\"failed to populate resolver cache from source certified-operators/openshift-marketplace: failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = \\\"transport: Error while dialing dial tcp 172.30.133.128:50051: connect: connection refused\\\"\"},{\"type\":\"CatalogSourcesUnhealthy\",\"status\":\"False\",\"reason\":\"AllCatalogSourcesHealthy\",\"message\":\"all available catalogsources are healthy\",\"lastTransitionTime\":\"2024-03-13T10:08:09Z\"}],\"lastUpdated\":\"2024-03-13T10:08:09Z\"}"
```

`#2`

```
time="2024-03-13T10:10:12Z" level=info msg="check completed" check=DeployableByOLM err="error: watch: could not retrieve the object apicurio-registry/apicurio-registry: failed to fetch the subscription apicurio-registry from namespace apicurio-registry: could not retrieve subscription: apicurio-registry/apicurio-registry: client rate limiter Wait returned an error: context deadline exceeded" result=ERROR
```

`#3`

```
time="2024-03-13T10:10:12Z" level=error msg="image does not appear to be pinned" error="a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: quay.io/apicurio/apicurio-registry-operator:1.1.1" image="quay.io/apicurio/apicurio-registry-operator:1.1.1"
time="2024-03-13T10:10:12Z" level=info msg="check completed" check=BundleImageRefsAreCertified err="no digests specified" result=ERROR
```

**Comment by Allda** [comment]
We are using a [preflig](https://github.com/redhat-openshift-ecosystem/openshift-preflight) for the operator dynamic test. I wasn't able to reproduce this failure locally and a test passed on my cluster.

@acornett21 Can you please check the preflight output to see what might be wrong here?
```
export PFLT_INDEXIMAGE=quay.io/community-operator-pipeline-prod/catalog:v4.16-b2294c9d102e9ef111802939a4efbfc4fadeeb90
preflight --loglevel trace check operator quay.io/community-operator-pipeline-prod/apicurio-registry:1.1.1-v2.5.9.final-b2294c9d102e9ef111802939a4efbfc4fadeeb9

{
    "image": "quay.io/community-operator-pipeline-prod/apicurio-registry:1.1.1-v2.5.9.final-b2294c9d102e9ef111802939a4efbfc4fadeeb90",
    "passed": true,
    "certification_hash": "d41d8cd98f00b204e9800998ecf8427e",
    "test_library": {
        "name": "github.com/redhat-openshift-ecosystem/openshift-preflight",
        "version": "1.9.1",
        "commit": "f19c2a2f587f9890d45ef8b9c13503a4c03f3218"
    },
    "results": {
        "passed": [
            {
                "name": "ScorecardBasicSpecCheck",
                "elapsed_time": 16223,
                "description": "Check to make sure that all CRs have a spec block."
            },
            {
                "name": "ScorecardOlmSuiteCheck",
                "elapsed_time": 4230,
                "description": "Operator-sdk scorecard OLM Test Suite Check"
            },
            {
                "name": "DeployableByOLM",
                "elapsed_time": 69832,
                "description": "Checking if the operator could be deployed by OLM"
            },
            {
                "name": "ValidateOperatorBundle",
                "elapsed_time": 77,
                "description": "Validating Bundle image that checks if it can validate the content and format of the operator bundle"
            },
            {
                "name": "RequiredAnnotations",
                "elapsed_time": 67,
                "description": "Checks that the CSV has all of the required feature annotations."
            }
        ],
        "failed": [],
        "errors": []
    }
}

```

**Comment by jsenko** [comment]
@Allda Thank you for the help!

**Pull request merged**
