### PR TITLE
operator ibm-block-csi-operator-community (1.11.2)

### PR DESCRIPTION
**Pull request by kasserater**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-via-pr.md)?
* [x] Are you familiar with our [operator pipeline](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/community-operator-pipeline.md)?
* [x] Have you tested your Operator with all Custom Resource Definitions [packaging](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md)?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/operator-ci-yaml.md##Operator-versioning)?
* [x] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#operator-icon) set?

### Your submission should not

* [x] Add more than one operator bundle per PR
* [x] Modify any operator
* [x] Rename an operator
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by csiblock** [comment]
this is failing for an unclear reason, and also not allowing to mark LGTM flag
opened issue [4543](https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/4543)

**Comment by kasserater** [comment]
@jfrancin please note that @ArbelNathan already attempted to mark with /lgtm flag last week
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4542#issuecomment-2112051959

**Comment by jfrancin** [comment]
1.11.1 does indeed exist. But only in the v4.13 bundle index. It doesn't exist in the OperatorHubs for RHOCP 4.14 and 4.15.

The 1.11.1 version's annotations.yaml file contains: `com.redhat.openshift.versions="v4.10-v4.13"`.
The 1.11.2 version's annotations.yaml file contains: `com.redhat.openshift.versions="v4.13-v4.15"`.

Since the 1.11.1, the version being replaced, does not exist in 4.14 or 4.15, the `replaces` directive cannot be satisfied, as the precursor version must exist in every version's operatorHub/bundle index.  You cannot use `replaces` in an operator bundle which supports a wider range of versions than the one being replaced.

Instead, change the `replaces: ibm-block-csi-operator.v1.11.1` to: a `skips` block:

```
spec:
  [...]
  version: 1.11.2
  skips: 
     - ibm-block-csi-operator.v1.11.1
  [...]

**Pull request merged**
