### PR TITLE
operator netobserv-operator (0.2.1)

### PR DESCRIPTION
**Pull request by jotak**
Signed-off-by: Joel Takvorian <jtakvori@redhat.com>

Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by jotak** [comment]
Hi @J0zi / @mvalarh ,
Could you help me understand what is wrong with the checks? I'm not sure to understand what the complains are about.
FWIW I tested the operator against 4.12 without issue. Tested deploying from custom catalog and with operator-sdk and verified upgrade with operator-sdk.

**Comment by jotak** [comment]
@J0zi thanks for your answer - I was already using a recent version of operator-sdk (v1.25.2, latest is v1.25.3) - I just tried with the latest just in case, but the generated bundle is identical, except for the operator-sdk version labels themselves of course.

I've just added the openshift versions label as I realized they were added in a previous commit ( https://github.com/redhat-openshift-ecosystem/community-operators-prod/commit/a315638cb033110f97d743ee0172dade2c1abd49 )

My last commit might be wrong, if we want to support both 4.12 and previous openshift should we proceed differently?

**Comment by jotak** [comment]
By having this annotation:

```
  com.redhat.openshift.versions: "v4.8-v4.11"
```

does it mean it won't install on 4.12?

**Comment by mariomac** [comment]
@J0zi might this be a bug?

According to the [deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25), v1.25 is deprecating autoscaling/v2beta1 but we were using v2beta2. Anyway we did the following to update to autoscaling/v2:

* We have replaced all the Go imports from [k8s.io/api/autoscaling/v2beta2](http://k8s.io/api/autoscaling/v2beta2) to [k8s.io/api/autoscaling/v2](http://k8s.io/api/autoscaling/v2).

* We also tried updating the groups in our manifests, e.g. in the [kubebuilder definitions](https://github.com/netobserv/network-observability-operator/blob/main/controllers/flowlogspipeline/flp_transfo_objects.go#L107) to update the manifests  [here](https://github.com/netobserv/network-observability-operator/blob/main/bundle/manifests/netobserv-operator.clusterserviceversion.yaml#L296) and [here](https://github.com/netobserv/network-observability-operator/blob/main/bundle/manifests/netobserv-operator.clusterserviceversion.yaml#L531), but no success.

* Also tried updating [k8s.io/api](http://k8s.io/api) and rest of client libraries from v0.24.0 to v0.25.5, but no success.
Is this any kind of bug or do we need to update the version information anywhere else? (couldn't find any other reference to autoscaling/v2beta1 but in the vendored libraries).

I have tried both with operator-sdk 1.25.3 and 1.26.0

Thank you!

**Comment by mariomac** [comment]
I found the issue. We had to update the apiVersion of our CatalogSource from operators.coreos.com/v1alpha1 to operators.coreos.com/v1

**Pull request merged**
