### PR TITLE
operators grafana-operator (4.0.2)

### PR DESCRIPTION
**Pull request by NissesSenap**
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### Updates to existing Operators

* [X] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [X] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [X] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [X] Have you tested an update to your Operator when deployed via OLM?
* [X] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [X] Modify more than one operator
* [X] Modify an Operator you don't own
* [X] Rename an operator - please remove and add with a different name instead
* [X] Modify any files outside the above mentioned folders
* [X] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [X] Description about the managed Application and where to find more information
2. [X] Features and capabilities of your Operator and how to use it
3. [X] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [X] Human readable name and 1-liner description about your Operator
* [X] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [X] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [X] Links to the maintainer, source code and documentation
* [X] Example templates for all Custom Resource Definitions intended to be used
* [X] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by NissesSenap** [comment]
Any pointers on this? All prow pipelines fail with the same error. Is there a beach name standard that i need to follow?
Any pointers would be great.

```
Cloning into 'community-operators'...

625

Cloned [OK]

626

Dir entered [OK]

627

BRANCH_NAME=origin/main

628

origin/update-grafana-operator-v4.0.2

629

error: pathspec 'origin/update-grafana-operator-v4.0.2' did not match any file(s) known to git

630

{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-11-22T21:49:48Z"}

631

error: failed to execute wrapped command: exit status 1
```

**Review by HubertStefanski — APPROVED** [review]

**Comment by HubertStefanski** [comment]
@J0zi @mvalarh Can you take a look at the CI?  It seems like it's failing on the same stage for all OpenShift versions, failing to check out the branch from @NissesSenap fork, trying it out locally (cloning and checking out the branch) seems to work fine.

P.S : Where can we find the code for these stages for future troubleshooting?

**Comment by J0zi** [comment]
bear with us, investigating...

**Pull request merged**
