### PR TITLE
operators opentelemetry-operator (0.37.1)

### PR DESCRIPTION
**Pull request by rkukura**
Signed-off-by: Robert Kukura <rkukura@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by rkukura** [comment]
@mvalarh - I see you reran the 4.9 test and it failed again with something like:

>     time="2021-11-01T14:32:49Z" level=error msg="UpdateStatus - error while setting CatalogSource status" error="Operation cannot be fulfilled on catalogsources.operators.coreos.com \"test-operators-ocs\": the object has been modified; please apply your changes to the latest version and try again" id=ggvmG source=test-operators-ocs

This doesn't mean much to me. Do you have any idea what the issue might be?

**Comment by J0zi** [comment]
> @mvalarh - I see you reran the 4.9 test and it failed again with something like:
> 
> > ```
> > time="2021-11-01T14:32:49Z" level=error msg="UpdateStatus - error while setting CatalogSource status" error="Operation cannot be fulfilled on catalogsources.operators.coreos.com \"test-operators-ocs\": the object has been modified; please apply your changes to the latest version and try again" id=ggvmG source=test-operators-ocs
> > ```
> 
> This doesn't mean much to me. Do you have any idea what the issue might be?

This is a normal behavior, it was applied later.

**Comment by J0zi** [comment]
I see operator ready and healty
```
    - Catalog source is up and READY            [OK]
    - Operatorgroup is present                  [OK]
    - Subscribed                                [OK]
    - Operator is in packagemanifests           [OK]
    - Operator startup                          [OK]
    - Operator stayed healthy after startup     [OK]
 ```
 It failed during deletion of resources. So folks can install your operator, but are unable to uninstall it.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/402/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.9-deploy-operator-on-openshift/1455200540676853760#1:build-log.txt%3A5764

**Comment by rkukura** [comment]
It looks like deleting this operator fails on OpenShift 4.9 since at least 0.33.0 (the version prior to this PR). With either 0.33.0 or 0.37.1, the operator appears to delete, but the opentelemetry-operator-controller-manager-* ReplicaSet is left in place and cannot be manually deleted. Deleting either version works fine on OpenShift 4.8. Has there been some OLM change in 4.9 that could explain this? Any other ideas?

**Comment by rkukura** [comment]
It seems both this 0.37.1 PR and the existing 0.33.0 bundle have issues on OpenShift 4.9. The opentelemetry-operator-controller-manager pod keeps restarting after logging errors like:

```
E1104 16:01:14.088765       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.OpenTelemetryCollector: failed to list *v1alpha1.OpenTelemetryCollector: Internal error occurred: error resolving resource
E1104 16:01:20.847304       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.OpenTelemetryCollector: failed to list *v1alpha1.OpenTelemetryCollector: Internal error occurred: error resolving resource
E1104 16:01:44.043345       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.OpenTelemetryCollector: failed to list *v1alpha1.OpenTelemetryCollector: Internal error occurred: error resolving resource
E1104 16:02:25.370013       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.OpenTelemetryCollector: failed to list *v1alpha1.OpenTelemetryCollector: Internal error occurred: error resolving resource
{"level":"error","ts":1636041784.8509786,"logger":"controller-runtime.manager.controller.opentelemetrycollector","msg":"Could not wait for Cache to sync","reconciler group":"opentelemetry.io","reconciler kind":"OpenTelemetryCollector","error":"failed to wait for opentelemetrycollector caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/manager/internal.go:696"}
{"level":"info","ts":1636041784.8514926,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}
{"level":"error","ts":1636041784.8515916,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"failed to list: Timeout: failed waiting for *v1alpha1.OpenTelemetryCollector Informer to sync"}
{"level":"error","ts":1636041784.8528888,"logger":"setup","msg":"problem running manager","error":"failed to wait for opentelemetrycollector caches to sync: timed out waiting for cache to be synced","stacktrace":"main.main\n\t/workspace/main.go:173\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
```

**Comment by rkukura** [comment]
The issue causing ci/prow/4.9-deploy-operator-on-openshift to fail is resolved by https://github.com/open-telemetry/opentelemetry-operator/pull/521. I am closing this PR, and will create a new PR updating to either 0.38.0 with the fixed  CRD, or to a subsequent release that includes the fix.

**Pull request closed without merging**
