### PR TITLE
operator project-quay (3.7.5)

### PR DESCRIPTION
**Pull request by quay-devel**
Add v3.7.5 to community operators

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
@J0zi @mvalarh Looks like the prow multi stage tests are failing for this PR and another one. Can you take a look?

**Comment by mvalarh** [comment]
@BillDett,@hdonnay,@crozzy,@kwestpharedhat,@ricardomaraschini,@kleesc,@Sunandadadi,@flavianmissi,@dmage,@syed,@harishsurf,@bcaton85,@jonathankingfc,@HammerMeetNail , please approve

**Review by HammerMeetNail — APPROVED** [review]
LGTM 👍

**Pull request merged**
