### PR TITLE
operator [CI] kubecost (1.106.0)

### PR DESCRIPTION
**Pull request by chipzoller**
Adds the Kubecost operator for v1.106.0. Tested successfully on an OCP v4.13.11 cluster.

First time submission so I'm sure I'm missing something.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by chipzoller** [comment]
So am I not able to push further changes to this PR such as remediating [this failure](https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/6226953515/job/16900681614?pr=3306#step:6:1036)?

**Comment by chipzoller** [comment]
> Current PR can be merged automatically, but there is missing `authorized-changes` label. One can find out more info [here](https://$%7BOPP_THIS_REPO_ORG%7D.github.io/$%7BOPP_THIS_REPO_NAME%7D/operator-ci-yaml/#reviewers).

The link in this bot's response is broken due to what looks like unsubstituted env vars.

**Comment by chipzoller** [comment]
> @linhlam-kc , please approve as you are original reviewer(s).
> 
>     * To add more contributors to `ci.yaml` follow instruction [here](https://$%7BOPP_THIS_REPO_ORG%7D.github.io/$%7BOPP_THIS_REPO_NAME%7D/operator-ci-yaml).
> 
>     * To approve follow instruction [here](https://$%7BOPP_THIS_REPO_ORG%7D.github.io/$%7BOPP_THIS_REPO_NAME%7D/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator)

This bot's response is also unfollowable for the same reason as [this one's](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3306#issuecomment-1724744698).

**Comment by linhlam-kc** [comment]
@chipzoller If I remember it correctly, you need to update this [CI.yaml](https://github.com/chipzoller/redhat-openshift-ecosystem-community-operators-prod/blob/kubecost-106/operators/kubecost/ci.yaml) file to add your Github alias and/or remove my alias

**Comment by chipzoller** [comment]
Argh, thanks, I did that in the initial commit but reverted it and didn't restore due to the request to squash. Added that just now. Can squash later if required.

**Review by linhlam-kc — APPROVED** [review]
LGTM

**Pull request merged**
