### PR TITLE
operator [N] [CI] kubecost (1.97.0)

### PR DESCRIPTION
**Pull request by mvalarh**
Dear @linhlam-kc,

Recently, there were some problem detecting correctly deprecation of api for k8s v1.25 (ocp v4.12) and we modified your annotations to limit some version of your operator for ocp `<v4.12`. This PR should revert this change. Please verify if your versions are working on `v4.12`. Please approve this change to be merged.

**Sorry for the inconvenience.**

Community operators team

PS: We also moved your `ci.yaml` to correct place

Signed-off-by: Martin Vala <mavala@redhat.com>

### CODE REVIEW

**Comment by linhlam-kc** [comment]
> Dear @linhlam-kc,
> 
> Recently, there were some problem detecting correctly deprecation of api for k8s v1.25 (ocp v4.12) and we modified your annotations to limit some version of your operator for ocp `<v4.12`. This PR should revert this change. Please verify if your versions are working on `v4.12`. Please approve this change to be merged.
> 
> **Sorry for the inconvenience.**
> 
> Community operators team
> 
> PS: We also moved your `ci.yaml` to correct place
> 
> Signed-off-by: Martin Vala [mavala@redhat.com](mailto:mavala@redhat.com)

Hi Martin, thank you for helping us making the changes. According to the change request, it seems that it makes our Operator is only compatible with OCP 4.9. Is it true? From my testing, it works fine for OCP up to v4.11

**Comment by J0zi** [comment]
@linhlam-kc after the change your operator will be available in all `v4.9+` indexes. So 4.9-4.12. Is your operator v4.12 ready?

Just FYI, to have `4.9` only, the syntax is the following: `com.redhat.openshift.versions: =v4.9` which is not the case here.

**Comment by mvalarh** [comment]
@linhlam-kc do you want to apply this change or can we close it?

**Comment by linhlam-kc** [comment]
> 

@mvalarh Thank you ! The changes looks good.

**Pull request merged**
