### PR TITLE
operators special-resource-operator (4.8.1)

### PR DESCRIPTION
**Pull request by dagrayvid**
### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [] Have you tested an update to your Operator when deployed via OLM?
* [X] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [X] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

### CODE REVIEW

**Comment by dagrayvid** [comment]
@J0zi it's not clear to me whether or not the failing test is due to some issue in the operator or not. Can you PTAL and let me know if there is something I can do?

**Comment by dagrayvid** [comment]
@J0zi @mvalarh Can you PTAL at the CI errors and give some guidance on whether there might be a problem from the operator that we can address for 4.6?

**Comment by J0zi** [comment]
@dagrayvid - pipeline tests are showing incompatibility with `OCP v4.6`. You can put `com.redhat.openshift.versions: "v4.8"` to `annotataion.yaml` and pipeline will not test nor release under `4.6`.

**Comment by dagrayvid** [comment]
Thanks @J0zi for now, I don't think we need 4.6 to work. We may look into it later.

**Pull request merged**
