### PR TITLE
operator [R] apicast-community-operator (0.1.0 0.1.1 0.2.1 0.2.2 0.3.0 0.3.1 0.4.0)

### PR DESCRIPTION
**Pull request by eguzki**
Signed-off-by: Eguzki Astiz Lezaun <eastizle@redhat.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by eguzki** [comment]
@mvalarh @J0zi asking for support here. 
Regarding the error in `Operator test / PR-traffic-light (pull_request_target) `: All the converted (from packagemanifets to bundle format) releases should be configured for `olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]'`. So I do not get the label issue for OCP 4.9, 4.10 and 4.11

```
fatal: [localhost]: FAILED! => changed=false 
  msg: '[''''][''Found label which is not supported.'', "[''apicast-community-operator:v0.1.0 => 4.9,4.10,4.11'', ''apicast-community-operator:v0.1.1 => 4.9,4.10,4.11'', ''apicast-community-operator:v0.2.1 => 4.9,4.10,4.11'', ''apicast-community-operator:v0.2.2 => 4.9,4.10,4.11'', ''apicast-community-operator:v0.3.0 => 4.9,4.10,4.11'', ''apicast-community-operator:v0.3.1 => 4.9,4.10,4.11'', ''apicast-community-operator:v0.4.0 => 4.9,4.10,4.11'']", '''']'
```

**Comment by J0zi** [comment]
@eguzki you are missing `com.redhat.openshift.versions: "v4.6-v4.8"` line in `annotations.yaml` for every relevant operator. 

This gives an instruction where you would like to release your opertor. OLM properties are related to upgrade for already released operator. In packegmanifest format there was no way to apply label, so we labeled it on the fly during backgroud conversion to bundle format.

**Comment by eguzki** [comment]
@J0zi asking for support here. 

I would not ask if I wouldn't have tried everything I can think of. :pray: 

Regarding the error:
```
Field spec.preserveUnknownFields,  Value 0xc000bb85c8: spec.preserveUnknownFields: Invalid value: true:  cannot set to true, set x-preserve-unknown-fields to true in  spec.versions[*].schema instead
```
I think this is due to CRD `apiextensions.k8s.io/v1beta1` version. I have run the validation tool (`operator-sdk bundle validate $BUNDLE_PATH --select-optional name=community` (operator-sdk v1.19.1) to other operators that I do not own with CRD `apiextensions.k8s.io/v1beta1` and the tool also reports that very same error. 

Any clue about how to fix that?

BTW, the new bundles (in coming PR's) for this and other operators we own have all CRD upgraded to `apiextensions.k8s.io/v1`

**Comment by J0zi** [comment]
Waiting for response from @camilamacedo86

**Comment by eguzki** [comment]
Heads up @J0zi @camilamacedo86 we are hitting same issue in 
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1424
* https://github.com/k8s-operatorhub/community-operators/pull/1476

**Comment by J0zi** [comment]
related to https://github.com/operator-framework/operator-sdk/issues/5688

**Comment by eguzki** [comment]
Not sure about what else needs to be done here. All checks passed.

Comparing to https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1424, `package-validated` label is missing in this PR

any clue @J0zi ?

**Pull request merged**
