### PR TITLE
operator gitlab-operator-kubernetes (0.20.5)

### PR DESCRIPTION
**Pull request by gl-distribution-oc**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by acornett21** [comment]
@mporrato @Allda Do you know why the tests are no longer honoring the OCP versions that is in the pull requests `annotation.yaml` file? Thanks.

**Comment by mporrato** [comment]
@acornett21 The tests are actually honoring the version annotation: you still see 4.8 and 4.9 in the list of checks but they are essentially no-ops and in fact they did not fail. I think that the orange test failed because we are doing some work in preparation for the release of 4.14 and at that specific moment some of the tags on the quay repo were temporarily removed.
The failure in the 4.14 prow job is also connected to the preparation for 4.14 but it won't block the merge.
I've kicked off the failed orange tests again.

**Comment by acornett21** [comment]
@mporrato Thanks for clarifying. I think it's confusing for partners to see tests for versions of OpenShift which they are not targeting in the PR. In this case OCP 4.13/4.14 are being executed. They might not block the merged, but the openshift-ci bot is going to make a comment that they failed and instructions to re-run, when they are not needed as you pointed out. 

@droopy4096 Can you clarify if this is where the confusion lies?

**Comment by droopy4096** [comment]
> @droopy4096 Can you clarify if this is where the confusion lies?

indeed it is confusing to see `ci/prow/4.14-deploy-operator-on-openshift — Job failed.` and see PR mot merged automatically .

**Comment by pursultani** [comment]
Is it possible to merge this PR manually? We are going to release the next one as well.

**Pull request merged**
