### PR TITLE
operator awx-operator (1.0.0)

### PR DESCRIPTION
**Pull request by rooftopcellist**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by J0zi** [comment]
@rooftopcellist Did you tested your operator on Openshift `v4.8` and `v4.9`? We are unable to start your operator there.

**Comment by rooftopcellist** [comment]
@J0zi I just tested a fresh install of the AWX Operator on an Openshift v4.8 cluster and it was successful, and also successfully deployed AWX.  

The test that failed suggested I should try an upgrade from the previous bundle, so I tried that against my v4.8 cluster and it succeeded.  

```
operator-sdk run bundle quay.io/ansible/awx-operator-bundle:0.30.0;
operator-sdk run bundle-upgrade quay.io/ansible/awx-operator-bundle:1.0.0
```

```
[chadams@chadams-work ~]$ operator-sdk run bundle-upgrade quay.io/ansible/awx-operator-bundle:1.0.0
INFO[0002] Found existing subscription with name awx-operator-v0-30-0-sub and namespace awx 
INFO[0002] Found existing catalog source with name awx-operator-catalog and namespace awx 
INFO[0011] Generated a valid Upgraded File-Based Catalog 
INFO[0019] Created registry pod: quay-io-ansible-awx-operator-bundle-1-0-0 
INFO[0019] Updated catalog source awx-operator-catalog with address and annotations 
INFO[0019] Deleted previous registry pod with name "quay-io-ansible-awx-operator-bundle-0-30-0" 
INFO[0030] Approved InstallPlan install-zr998 for the Subscription: awx-operator-v0-30-0-sub 
INFO[0030] Waiting for ClusterServiceVersion "awx/awx-operator.v1.0.0" to reach 'Succeeded' phase 
INFO[0030]   Waiting for ClusterServiceVersion "awx/awx-operator.v1.0.0" to appear 
INFO[0031]   Found ClusterServiceVersion "awx/awx-operator.v1.0.0" phase: Pending 
INFO[0033]   Found ClusterServiceVersion "awx/awx-operator.v1.0.0" phase: InstallReady 
INFO[0034]   Found ClusterServiceVersion "awx/awx-operator.v1.0.0" phase: Installing 
INFO[0044]   Found ClusterServiceVersion "awx/awx-operator.v1.0.0" phase: Succeeded 
INFO[0044] Successfully upgraded to "awx-operator.v1.0.0" 
```

Any ideas on what to try next?

**Comment by rooftopcellist** [comment]
@J0zi I bet this is because I set this for the minimum k8s version:

```
  MinKubeVersion: 1.22.15
```

Which is greater than the k8s version used on Openshift v4.8:

```
[chadams@chadams-work ~]$ oc version
Client Version: 4.6.8
Server Version: 4.8.53
Kubernetes Version: v1.21.11+5cc9227
```

The equivalent downstream bits have a supported OCP range of v4.10-v4.12 (and v4.13 when released).  So I will update this PR to reflect that.  I expect those v4.8/9 tests will now be skipped.  Sorry for the churn here.

**Pull request merged**
