### PR TITLE
operator [N] [CI] ossmconsole (0.1.0)

### PR DESCRIPTION
**Pull request by jmazzitelli**
This is the initial version for the new dev preview release of the new OpenShift Service Mesh Console.

Signed-off-by: John Mazzitelli <mazz@redhat.com>

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [x] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [x] Have you tested your Operator with all Custom Resource Definitions?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [x] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I'm going to update the metadata to include openshift version limits and to declare multi-arch support.

**Comment by jmazzitelli** [comment]
@J0zi @mvalarh I am not sure what else needs to get done for this to be merged. I don't see an `authorized-changes` label on here, which I assume that is because this is a `new-operator` (my username is in the [ci.yaml](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1613/files#diff-78a3da5c244bf707d89b4477b883a7b317abd47484998bff0a2405afa321e2efR5) file)

Let me know what I need to do (if anything) to get this published. We are going to announce this operator in a redhat blog post monday morning.

**Comment by mvalarh** [comment]
@jmazzitelli it should be published in 30 min from now

**Pull request merged**
