### PR TITLE
operator cert-manager (1.10.0-rc1)

### PR DESCRIPTION
**Pull request by wallrj**
Signed-off-by: Richard Wall <richard.wall@jetstack.io>

### CODE REVIEW

**Comment by wallrj** [comment]
Startup failure in openebs-operator causes  cert-manager tests to fail

```
Wait for the operator openebs-operator pod to start up
...
Operator startup                          [FAIL]
```

Full error report

```

{  "deploy-operator-on-openshift" pod "deploy-operator-on-openshift-deploy-operator" failed: the pod ci-op-0927kssp/deploy-operator-on-openshift-deploy-operator failed after 27m44s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
ce.
    See 'Wait for the operator openebs-operator pod to start up' step above.
    Also check, that the operator is not listed in running containers in 'Check all containers' step.
    In some cases step 'Output debug - catalog operator' can be helpful. Also check other debug outputs.
    -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

TASK [deploy_olm_operator_openshift_upstream : Report short prow summary] ******
ok: [localhost] => 
  prow_summary:
  - Catalog source is up and READY            [OK]
  - Operatorgroup is present                  [OK]
  - Subscribed                                [OK]
  - Operator is in packagemanifests           [OK]
  - Operator startup                          [FAIL]

TASK [deploy_olm_operator_openshift_upstream : Debug] **************************
ok: [localhost] => 
  operator_upgrade_testing_disabled: 'VARIABLE IS NOT DEFINED!: ''operator_upgrade_testing_disabled'' is undefined'

TASK [deploy_olm_operator_openshift_upstream : Debug] **************************
ok: [localhost] => 
  operator_upgrade_testing_on_openshift_disabled: 'true'

TASK [deploy_olm_operator_openshift_upstream : Fail when Operator deployment with OLM failed] ***
fatal: [localhost]: FAILED! => changed=false 
  msg: Operator deployment with OLM failed, expand log and check logs from the bottom to the top ^

PLAY RECAP *********************************************************************
localhost                  : ok=175  changed=82   unreachable=0    failed=1    skipped=90   rescued=0    ignored=9   

Reporting ...
Variable summary:
OP_NAME=cert-manager
OP_VER=1.10.0-rc1
Ansible failed, see output above
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-25T12:43:19Z"}
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/deploy-operator
Link to job on registry info site: https://steps.ci.openshift.org/job?org=redhat-openshift-ecosystem&repo=community-operators-prod&branch=main&test=deploy-operator-on-openshift&variant=4.9}

```

-- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/1777/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.9-deploy-operator-on-openshift/1584872808293339136

**Comment by J0zi** [comment]
@wallrj please bear in mind that the operator works only for `v4.6` (which we stop testing as of today) and `v4.11`. You can fix  operator for failing clusters or set label to release only on `v4.11+`.

**Comment by J0zi** [comment]
@wallrj did you tested `cert-manager` on Openshift `v4.10`? I have no problem with `openebs-operator` on `v4.10`. So issue seems to be with `cert-manager` then.

**Comment by wallrj** [comment]
> @wallrj did you tested `cert-manager` on Openshift `v4.10`? I have no problem with `openebs-operator` on `v4.10`. So issue seems to be with `cert-manager` then.

I must admit that I haven't tested on on OpenShift v4.10.

I pointed the finger at openebs-operator because it appears at the top of the test failure log:
image
-- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/1777/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.10-deploy-operator-on-openshift/1585182368203804672

I don't know how to interpret the test failure logs.

```
...
Reporting ...
Variable summary:
OP_NAME=cert-manager
OP_VER=1.10.0-rc1
Ansible failed, see output above
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-10-26T09:13:52Z"}
error: failed to execute wrapped command: exit status 1
}
```
What do you make of that?
Can you see what the problem might be when you look at the test logs?

I  don't understand why the tests should succeed for OpenShift v4.6 and v4.11 but not for the versions in between.

**Comment by J0zi** [comment]
@wallrj there is no `openebs` operator involved. It is just text hint, which should contain variable with the name of your operator. I will fix it.
On the other hand, you can try your operator on `v4.10` and debug the reason it is failing. Then you have 2 options. Either fix it or just don't release on versions which are not working by applying label `com.redhat.openshift.versions: "v4.11"` like [there](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/community-kubevirt-hyperconverged/1.7.0/metadata/annotations.yaml#L8).

**Comment by wallrj** [comment]
Ah, I've found some build logs with some evidence that the cert-manager Pods are failing to start

/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/1777/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.10-deploy-operator-on-openshift/1585182368203804672/artifacts/deploy-operator-on-openshift/deploy-operator/

```
FAILED - RETRYING: [localhost]: Wait for the operator cert-manager pod to start up (1 retries left).

TASK [deploy_olm_operator_openshift_upstream : Wait for the operator cert-manager pod to start up] ***
fatal: [localhost]: FAILED! => changed=true 
  attempts: 90
  cmd: /tmp/oc-YRgbAInGLE9uPyoVKk63/bin/oc get pods -n test-operators| grep cert-manager | grep Running
  delta: '0:00:00.257421'
  end: '2022-10-26 09:13:13.026604'
  msg: non-zero return code
  rc: 1
  start: '2022-10-26 09:13:12.769183'
  stderr: No resources found in test-operators namespace.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
...ignoring
```

```
TASK [deploy_olm_operator_openshift_upstream : Get deployments] ****************
changed: [localhost] => changed=true 
  cmd: /tmp/oc-YRgbAInGLE9uPyoVKk63/bin/oc get deployments -n test-operators | grep cert-manager | cut -f1 -d' '| xargs -I{} /tmp/oc-YRgbAInGLE9uPyoVKk63/bin/oc describe deployment {} -n test-operators
  delta: '0:00:01.837420'
  end: '2022-10-26 09:13:20.173051'
  msg: ''
  rc: 0
  start: '2022-10-26 09:13:18.335631'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Name:                   cert-manager
    Namespace:              test-operators
...
                        support: The cert-manager maintainers
      Service Account:  cert-manager
      Containers:
       cert-manager-controller:
        Image:      quay.io/jetstack/cert-manager-controller:v1.10.0
        Port:       9402/TCP
        Host Port:  0/TCP
        Args:
          --v=2
          --cluster-resource-namespace=$(POD_NAMESPACE)
          --leader-election-namespace=kube-system
        Environment:
          POD_NAMESPACE:             (v1:metadata.namespace)
          OPERATOR_CONDITION_NAME:  cert-manager.v1.10.0-rc1
        Mounts:                     <none>
      Volumes:                      <none>
    Conditions:
      Type             Status  Reason
      ----             ------  ------
      Available        False   MinimumReplicasUnavailable
      ReplicaFailure   True    FailedCreate
      Progressing      False   ProgressDeadlineExceeded
    OldReplicaSets:    <none>
    NewReplicaSet:     cert-manager-84bbb97445 (0/1 replicas created)
    Events:
      Type    Reason             Age   From                   Message
      ----    ------             ----  ----                   -------
      Normal  ScalingReplicaSet  15m   deployment-controller  Scaled up replica set cert-manager-84bbb97445 to 1
```

I can't find any logs among the prow artifacts that show why the Pods might be failing to start.

I'll try and test this manually on OpenShift v4.10.

**Comment by wallrj** [comment]
> Literally it is failing to create the first replica in the namespace. So no logs from non existing pod. `ReplicaFailure True FailedCreate`

Sure. But I was looking for a log of all the Kubernetes Events.
Or something else to say *why* it failed to create the Pod.

**Comment by wallrj** [comment]
I created a crc cluster and installed cert-manager using the static manifests and found that the deployments were failing due to a [security context constraint](https://docs.openshift.com/container-platform/4.11/authentication/managing-security-context-constraints.html). 

I guess this is was caused by the following PR which changed the security contexts of the cert-manager pods
 * https://github.com/cert-manager/cert-manager/pull/5259

```
[crc@crc-4-9 ~]$ oc apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.yaml

[crc@crc-4-9 ~]$ oc -n cert-manager get deploy cert-manager -o yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
...
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9402"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: cert-manager
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/version: v1.10.0
...
status:
  conditions:
...
  - lastTransitionTime: "2022-11-01T09:41:41Z"
    lastUpdateTime: "2022-11-01T09:41:41Z"
    message: 'pods "cert-manager-84bc577876-qzbnf" is forbidden: unable to validate
      against any security context constraint: [pod.metadata.annotations.seccomp.security.alpha.kubernetes.io/pod:
      Forbidden: seccomp may not be set pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/cert-manager-controller:
      Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable by
      user or serviceaccount provider "nonroot": Forbidden: not usable by user or
      serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user or
      serviceaccount provider "machine-api-termination-handler": Forbidden: not usable
      by user or serviceaccount provider "hostnetwork": Forbidden: not usable by user
      or serviceaccount provider "hostaccess": Forbidden: not usable by user or serviceaccount
      provider "privileged": Forbidden: not usable by user or serviceaccount]'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
...

```

**Pull request merged**
