### PR TITLE
operator kubecost (2.1.0)

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: chipzoller <chipzoller@gmail.com>

Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by chipzoller** [comment]
I need assistance here, please. The bot is complaining about bundles with different names. The only reference to that I can find is the 1.106.0 operator which has the bundle name `kubecost-operator`. The 2.1.0 operator in this PR uses the `kubecost` name established by all others. I cannot change the bundle name of an existing in this PR and nor do I seem to be able to do so in a new PR (see PR #4088).

How do I proceed here with this new check which was not present when I submitted the previous version of the operator (see PR #3662)?

**Comment by tomasbakk** [comment]
> I need assistance here, please. The bot is complaining about bundles with different names. The only reference to that I can find is the 1.106.0 operator which has the bundle name `kubecost-operator`. The 2.1.0 operator in this PR uses the `kubecost` name established by all others. I cannot change the bundle name of an existing in this PR and nor do I seem to be able to do so in a new PR (see PR #4088).
> 
> How do I proceed here with this new check which was not present when I submitted the previous version of the operator (see PR #3662)?

Hello  @chipzoller  I'll have a look at it for you.

**Comment by chipzoller** [comment]
Thank you, @tomasbakk

**Comment by chipzoller** [comment]
@tomasbakk any help?

**Comment by tomasbakk** [comment]
@chipzoller I would need a little more time. I am still trying to find the solution for it.

**Comment by chipzoller** [comment]
Following up here to see if there have been any developments. We have several users awaiting this operator.

**Comment by jsenko** [comment]
I have the same issue here https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4174 . Can anyone take a look please?

**Comment by Allda** [comment]
@chipzoller Your operator is using a mix of names across different versions:
```
('kubecost-operator', '1.106.2'), ('kubecost', '1.99.0'), ('kubecost', '1.97.0'), ('kubecost', '1.106.0'), ('kubecost-operator', '1.107.1')
```
Do you want to continue using different names? This situation happened because the previous versions of a release pipeline didn't check the rule.

We have a couple of options here.. 
 - Resubmit operators to unify the names.
 - Manually change the names (this might break something in the future)
 - Add a test exception for this operator and continue using a mix of names.

Let me know which option you prefer.

**Comment by chipzoller** [comment]
Standardize name as "kubecost". The errors were probably mine so let's just update the necessary ones.

**Comment by chipzoller** [comment]
@Allda, can you just go ahead on the backend and standardize any "wrong" names so we can move forward?

**Comment by Allda** [comment]
@chipzoller The PR with the fix has been created and will be merged soon. As I mentioned in the previous comment this manuall workaroudn and fix might potentially break something in the future.

Once the PR is merged I'll retrigger a tests on this one. Please sign your commit as it is one of the requirements.

**Comment by chipzoller** [comment]
Thanks for your help, @Allda. I'll test this when it appears in the OpenShift catalog tomorrow.

**Pull request merged**
