### PR TITLE
operators [R] [CI] eclipse-che (7.44.0)

### PR DESCRIPTION
**Pull request by nickboldt**
switch all previous releases to semver (remove replaces: directive)

Change-Id: If494a351f2d618bba3b2af89771c850203e3fa4f
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
replacement for https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/901 as I can't push a fix into that PR.

**Comment by J0zi** [comment]
Hi @nickboldt , regarding supported clusters you mentioned. You should add line `com.redhat.openshift.versions: v4.8`  to `annotations.yaml`  for every affected version
after successfully merging the first PR in row, do not forget to close and reopen next in row to restart tests.

**Comment by nickboldt** [comment]
> Hi @nickboldt , regarding supported clusters you mentioned. You should add line `com.redhat.openshift.versions: v4.8` to `annotations.yaml` for every affected version after successfully merging the first PR in row, do not forget to close and reopen next in row to restart tests.

Already done for applicable versions: https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/eclipse-che/7.42.0/metadata/annotations.yaml#L27

Please merge this PR.

**Pull request merged**
