### PR TITLE
operator [N] [CI] pubsubplus-eventbroker-operator (1.0.0)

### PR DESCRIPTION
**Pull request by bczoma**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [ ] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [ ] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [ ] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by bczoma** [comment]
Hi @mporrato or @Allda, trying to understand the fails reported on our new operator.
Can you kindly help how to proceed from here?

There are two consistent fails (let the tests run three times):
- ci/prow/4.10-deploy-operator-on-openshift
    - Cause `error pulling image quay.io/openshift-community-operators/pubsubplus-eventbroker-operator:v1.0.0`
- ci/prow/4.14-deploy-operator-on-openshift
    - Cause: `violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false ...`

The tests pass on OpenShift 4.8, 4.9., 4.11, 4.12, 4.13.

I'm assuming test systems only differ in OpenShift versions

1. The first fail seems to be an environmental issue on that test system as other systems had no issue with image pulling.
2. Also not sure is the second fail is valid. Here is the relevant snippet from the `clusterserviceversion.yaml` submitted, and I can verify it on the operator pod in my local deployment:

```
      deployments:
        name: pubsubplus-eventbroker-operator
        spec:
          template:
            spec:
              containers:
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
```

**Comment by mporrato** [comment]
@bczoma don't worry about the 4.14 test: there was an issue in the CI configuration that has now been fixed, but for now failures in 4.14 won't block the merge yet.
Not sure about the failure on 4.10. I'll kick off a retest for now.

**Comment by bczoma** [comment]
Thank you @mporrato . For the 4.10 fail, wondering if it has to do with the recent changes related to using quay.io. Just a guess though.

**Comment by bczoma** [comment]
Hi @mporrato sorry for keeping getting back to you. It seems it is beyond my control that OpenShift 4.10 test system cannot reach the container that others can. At least it keeps failing repeatedly on this after I kicked off another retest.

**Comment by bczoma** [comment]
Hi @mporrato , @tomasbakk,
Following up on this as I seem to be stuck. Raised related issue #2858 as it still looks like a test system issue to me.
Could you kindly advise?

**Comment by bczoma** [comment]
Hi @mporrato , @tomasbakk, we ended up removing OpenShift 4.10 from the supported versions list, given https://access.redhat.com/support/policy/updates/openshift#dates, and adjusted to support from 4.11.

With that there seem to be no issue from the automated checks.

Let me know if anything is required for the next steps please - thank you!

**Pull request merged**
