### PR TITLE
operator awx-operator (2.12.2)

### PR DESCRIPTION
**Pull request by awx-auto**
operator awx-operator (2.12.2)

### CODE REVIEW

**Comment by mmacdo02-tufts** [comment]
Anyway this can eventually get merged into main?  Wanting to upgrade to awx-operator 2.12.2 so that I can upgrade to AWX to fix a bug (https://github.com/ansible/awx/issues/14885)

**Comment by tothf** [comment]
> Anyway this can eventually get merged into main? Wanting to upgrade to awx-operator 2.12.2 so that I can upgrade to AWX to fix a bug ([ansible/awx#14885](https://github.com/ansible/awx/issues/14885))

I've managed to merge 2.12.1 which will upgrade to AWX 23.8.1 and that does not have the bug. We are still on 2.12.0 but manually set the image to quay.io/ansible/awx:23.8.1 as a workaround.

Will check later why static est fails with "dangling version 2.12.0" and try to merge it again.

**Comment by rooftopcellist** [comment]
I don't understand why we are getting this error:

```
check_dangling_bundles	Channel alpha has dangling bundles: {Bundle(awx-operator/2.12.0)}
```

The correct replaces was set: 
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4095/files#diff-94c467a670a33c7dffe734954719af3b714d57bc9041eb480c93055c60e16d5dR1446
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4049/files#diff-83963cee3a559fa310da687b3e7d7cebd72129900a35efba7527e1d9a41b6f91R1446
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4028/files#diff-6d64673b0105990e9e7a2ef0be7dd8b2c3a480e3937ea2accbcbbbc3c127d249R1446


@haripate @mporrato Any advice?

**Comment by kurokobo** [comment]
@TheRealHaoLiu @rooftopcellist @tothf 
The source branch [publish-awx-operator-2.12.2](https://github.com/awx-auto/community-operators-prod/tree/publish-awx-operator-2.12.2) does not contain 2.12.1, so test failed since correct upgrade path from 2.12.0 to 2.12.2 can not be determined.

**Comment by kurokobo** [comment]
I know nothing about repo under awx-auto but rebasing source branch may solve the issue I guess

```bash
$ git checkout publish-awx-operator-2.12.2
Switched to branch 'publish-awx-operator-2.12.2'
Your branch is up to date with 'awx-auto/publish-awx-operator-2.12.2'.

$ optool check awx-operator
failure: check_upgrade(Operator(awx-operator)): Channel alpha has dangling bundles: {Bundle(awx-operator/2.12.0)}

$ optool ls awx-operator | grep 2.12
  Bundle(awx-operator/2.12.0)
  Bundle(awx-operator/2.12.2)

$ ls -l operators/awx-operator | grep 2.12
drwxrwxr-x. 5 kuro kuro  52 Mar  6 01:38 2.12.0
drwxrwxr-x. 5 kuro kuro  52 Mar  6 01:49 2.12.2
```

**Comment by Denney-tech** [comment]
Nice find @kurokobo! This PR is definitely stale and needs to be rebased before it can pass the pipeline checks. That being said, it looks safe to merge as as-is.

**Comment by rooftopcellist** [comment]
@kurokobo @Denney-tech thank you for pointing this out.  This PR must have been created before 2.12.1 and/or 2.12.0 were merged.  

I created a new PR here so that CI will pass:
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4134

Same changes, just rebased.

**Comment by rooftopcellist** [comment]
Feel free to close this PR.  I don't have permissions to do so, and the person who does is out for the day.

**Pull request closed without merging**
