### PR TITLE
operators universal-crossplane (1.6.1-up.1)

### PR DESCRIPTION
**Pull request by turkenh**
Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Review by muvaf — APPROVED** [review]
LGTM!

**Comment by mvalarh** [comment]
@turkenh can you please fix: https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/4883448404?check_suite_focus=true#step:6:1072

**Comment by turkenh** [comment]
> @turkenh can you please fix: https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/4883448404?check_suite_focus=true#step:6:1072

@mvalarh need some guidance on that: https://github.com/k8s-operatorhub/community-operators/pull/619#issuecomment-1018434683

Could you help?

**Comment by turkenh** [comment]
@mvalarh removed service accounts from the manifest and previously failing kiwi test passed this time, but now all deployment tests failed. 

Tested locally and observed exactly the same behaviour, e.g. `operator-sdk bundle validate` works but when I try to deploy, no pods created because service account not created at all. 😕

**Comment by J0zi** [comment]
@turkenh looks like service account name has some conflict. Like 2 different service accounts using the same name. The error is ` sa name cannot match service account defined for deployment spec in CSV`

**Comment by turkenh** [comment]
> @turkenh looks like service account name has some conflict. Like 2 different service accounts using the same name. The error is ` sa name cannot match service account defined for deployment spec in CSV`

Let me summarize, I am confused because:
- There are no such duplicated service accounts in the bundle
- Even the [existing latest version](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/486) fails with the same error locally (with `operator-sdk bundle validate`)
- Following @estroz suggestion [in this comment](https://github.com/operator-framework/operator-sdk/issues/5244#issuecomment-951127182), I [removed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/657/commits/6e1b10cda2812b4d172728978ea699ca485efe79) service account manifests. Validation passed this time but the installation failed on all jobs and reproduced locally that it is because there is no SA, **_OLM didn't create the service accounts referenced in CSV_**

So, I am kind of stuck at this point regarding how to proceed.

**Comment by J0zi** [comment]
@turkenh If I understand correctly, you would like to include service account on one hand and keep validator satisfied on the other hand. Maybe using different name for service account could help. Validate it by SDK.

**Comment by J0zi** [comment]
@turkenh are you able to install the operator on OCP?

**Comment by J0zi** [comment]
@turkenh closing due to no activity, feel free to reopen any time.

**Pull request closed without merging**
