### PR TITLE
Remove GitLab Runner Operator versions without `com.redhat.openshift.versions`

### PR DESCRIPTION
**Pull request by bertoldia**
This PR is related to case number 03428081 in https://connect.redhat.com/support/technology-partner/

Versions of GitLab Runner Operator before 1.11 do not include the `com.redhat.openshift.versions` label. Starting with version 1.11 `com.redhat.openshift.versions` was added with the value `4.8-4.10`. This means that GitLab Runner Operators versions before 1.11 incorrectly claim to support OpenShift versions <4.8 and >4.10. To avoid confusion, we'd like to remove GitLab Runner Operator version which don't specify `com.redhat.openshift.version`.

Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### Updates to existing Operators

* [ ] ~~Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?~~
* [ ] ~~Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?~~
* [ ] ~~Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?~~
* [ ] ~~Have you tested an update to your Operator when deployed via OLM?~~
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [x] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] ~~Description of the managed Application and where to find more information~~
2. [ ] ~~Features and capabilities of your Operator and how to use it~~
3. [ ] ~~Any manual steps about potential pre-requisites for using your Operator~~

### Operator Metadata should contain

* [ ] ~~Human readable name and 1-liner description about your Operator~~
* [ ] ~~Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>~~
* [ ] ~~One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>~~
* [x] Links to the maintainer, source code and documentation
* [ ] ~~Example templates for all Custom Resource Definitions intended to be used~~
* [ ] ~~A quadratic logo~~

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

### CODE REVIEW

**Comment by bertoldia** [comment]
Hi @J0zi @mvalarh a handful of tests have failed but I'm not sure what to make of them or how to proceed. Could you provide some guidance please? Thanks in advance.

**Comment by mporrato** [comment]
@bertoldia since you are removing all versions prior to 1.11.0, you should remove `replaces: gitlab-runner-operator.v1.10.0` from 1.11.0's CSV.

**Comment by bertoldia** [comment]
Hi @J0zi, @mvalarh This PR is ready to merge. Is one of you able to do that? Thanks.

**Comment by mvalarh** [comment]
@ggeorgiev-gitlab , please approve as you are original reviewer

**Comment by mvalarh** [comment]
@bertoldia yes we can do it but we prefer that reviewer listed in `ci.yaml` file approve it.

**Review by ggeorgiev-gitlab — APPROVED** [review]

**Comment by ggeorgiev-gitlab** [comment]
Btw the bot's link from https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2234#issuecomment-1431728299 doesn't work

**Comment by bertoldia** [comment]
Thanks @J0zi, @mvalarh, @ggeorgiev-gitlab :+1:

**Pull request merged**
