### PR TITLE
operator alloydb-omni-operator (1.1.1)

### PR DESCRIPTION
**Pull request by Manvi1203**
Signed-off-by: Manvi Gupta <guptamanvi@google.com>
Co-authored-by: Jahnavi Malhotra <jahnaviii@google.com>

Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-via-pr.md)?
* [ ] Are you familiar with our [operator pipeline](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/community-operator-pipeline.md)?
* [ ] Have you tested your Operator with all Custom Resource Definitions [packaging](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md)?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/operator-ci-yaml.md##Operator-versioning)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#operator-icon) set?

### Your submission should not

* [ ] Add more than one operator bundle per PR
* [ ] Modify any operator
* [ ] Rename an operator
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by tomasbakk** [comment]
Pipeline failed due to missing required annotations. Once fixed by the user, should go through.

**Comment by Manvi1203** [comment]
@tomasbakk in our evaluate-preflight-result, the "Checking if the operator could be deployed by OLM" fails. We tried running the bundle via operator-sdk run bundle command, it works fine. Would you be able to help us debug this issue or point us in the right direction to investigate further?

```
operator-sdk run bundle docker.io/manvi1203/alloydbomni-operator-try-21-bundle:v1.1.1
INFO[0012] Creating a File-Based Catalog of the bundle "docker.io/manvi1203/alloydbomni-operator-try-21-bundle:v1.1.1" 
INFO[0015] Generated a valid File-Based Catalog         
INFO[0021] Created registry pod: docker-io-manvi1203-alloydbomni-operator-try-21-bundle-v1-1-1 
INFO[0021] Created CatalogSource: alloydbomni-operator-catalog 
INFO[0022] Created Subscription: alloydbomni-operator-v1-1-1-sub 
INFO[0042] Approved InstallPlan install-z22kr for the Subscription: alloydbomni-operator-v1-1-1-sub 
INFO[0042] Waiting for ClusterServiceVersion "default/alloydbomni-operator.v1.1.1" to reach 'Succeeded' phase 
INFO[0044]   Found ClusterServiceVersion "default/alloydbomni-operator.v1.1.1" phase: Pending 
INFO[0056]   Found ClusterServiceVersion "default/alloydbomni-operator.v1.1.1" phase: InstallReady 
INFO[0061]   Found ClusterServiceVersion "default/alloydbomni-operator.v1.1.1" phase: Installing 
INFO[0071]   Found ClusterServiceVersion "default/alloydbomni-operator.v1.1.1" phase: Succeeded 
INFO[0071] OLM has successfully installed "alloydbomni-operator.v1.1.1"
```

**Comment by Allda** [comment]
Closing due to a lack of activity in this PR. Feel free to reopen if you want to continue.

**Pull request closed without merging**
