### PR TITLE
operators [R] project-quay (3.7.0-rc.1 3.7.0-rc.2)

### PR DESCRIPTION
**Pull request by HammerMeetNail**
* Resolves issue with missing clair tag

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
@J0zi @mvalarh I'm in the list of reviewers, shouldn't the `authorized_label` be added automatically now that our tests have passed?

**Review by jonathankingfc — APPROVED** [review]
LGTM

**Comment by mvalarh** [comment]
@HammerMeetNail I don't see your username in https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/project-quay/ci.yaml

**Comment by HammerMeetNail** [comment]
> @HammerMeetNail I don't see your username in https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/project-quay/ci.yaml

Oh darn, is it supposed to be the Github username? I'll need to update that for everyone.

**Pull request merged**
