### PR TITLE
operator trustify-operator (0.1.0-alpha.1)

### PR DESCRIPTION
**Pull request by carlosthe19916**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by carlosthe19916** [comment]
Could someone help me to trigger the tests please?

**Comment by carlosthe19916** [comment]
@Allda @ezopezo @haripate @mporrato @tomasbakk could you help me with this PR please?

**Comment by haripate** [comment]
@carlosthe19916 I will look into the issue.

**Comment by haripate** [comment]
These changes are merged by PR #4714. Did you rebase this branch?

**Comment by carlosthe19916** [comment]
@haripate my sincere apologies for having taken your time. Indeed, the mistake was on my side. Now my operator is in the main branch. Thank you very much!!!

**Comment by haripate** [comment]
No problem. The release pipeline hasn't been triggered on the merged PR #4714. Do you want me to help with that?

**Comment by carlosthe19916** [comment]
> No problem. The release pipeline hasn't been triggered on the merged PR #4714. Do you want me to help with that?

Yes please. I truly appreciate your kind help. Thank you very much!!!!!

**Pull request closed without merging**
