### PR TITLE
Revert PR hazelcast-platform-operator (5.12.0)

### PR DESCRIPTION
**Pull request by devOpsHelm**
This reverts commit d3749cb9ec29bea5f80aaa56017e312d52ea9a26.

Signed-off-by: devOpsHelm <devopshelm@hazelcast.com>

Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

* [x] Are you familiar with our [contribution guidelines](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-via-pr.md)?
* [x] Are you familiar with our [operator pipeline](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/community-operator-pipeline.md)?
* [ ] Have you tested your Operator with all Custom Resource Definitions [packaging](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md)?
* [x] Have you tested your Operator in all supported [installation modes](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/operator-ci-yaml.md##Operator-versioning)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [x] Is your submission [signed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-prerequisites.md#sign-your-work)?
* [x] Is operator [icon](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#operator-icon) set?

### Your submission should not

* [x] Add more than one operator bundle per PR
* [ ] Modify any operator
* [ ] Rename an operator
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by devOpsHelm** [comment]
Hi @J0zi @mvalarh
Could you please check this PR and tell me what is wrong here? What should I do to revert the commit and remove [hazelcast-operator-5.12.0]

Currently, it's a kind of release blocker for our operator.

**Comment by devOpsHelm** [comment]
Hi @J0zi @mvalarh @Allda @mporrato 
Could you please check this PR and tell me what is wrong here? What should I do to revert the commit and remove [hazelcast-operator-5.12.0]

Currently, it's a kind of release blocker for our operator.

**Comment by devOpsHelm** [comment]
> @devOpsHelm you cannot change existing bundles. You will have to release a new bundle.
Hi @mporrato, but this bundle is not correct and won't work for users. I need to create new 5.12.0 but it won't be possible because 5.12.0 already exist and we need to keep versioning. Why it's a problem to remove?
For example this one removed https://github.com/k8s-operatorhub/community-operators/pull/4266 and certified operator will be removed as well https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3843

**Comment by mporrato** [comment]
This repo's ci has now been [unified](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/3679) with the isv certification pipeline and it has inherited some of its restrictions.
Immutability of existing bundles is one of those restrictions.

**Comment by devOpsHelm** [comment]
> This repo's ci has now been [unified](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/3679) with the isv certification pipeline and it has inherited some of its restrictions. Immutability of existing bundles is one of those restrictions.

Ok then, can you please advice how can I release 5.12.0 version?

**Comment by mporrato** [comment]
You will have to release a new bundle.

**Comment by hasancelik** [comment]
Hi @mporrato @Allda @J0zi @mvalarh,

I am from the Hazelcast team. 

We did not know about the policy change, you mentioned me in [the announcement](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/3679) but I did not receive any notification so that's why we did not modify our release script to prevent these kind of situations. And also at the announcement, you mentioned that you introduced this policy to prevent some problems at user-side:

>Bundle Removal Restriction: Removal or update of a bundle is no longer allowed. This restriction ensures that operator users won't end up with a broken operator in case an operator is removed from an index.

but we have just released this version few hours ago so no one is using it right now.

Releasing the new version(5.13) is not possible for us now because we have a public roadmap that has already been announced to our customers. It will create huge confusion on their side. I could see some revert PRs which were created after the announcement:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4221

Could you make an exception for us just for once? We have already started to change our release script to make it compatible with your policy.

Thanks,

**Comment by mporrato** [comment]
> but we have just released this version few hours ago so no one is using it right now.

That's why I am suggesting to release a new bundle to fix the issue as soon as possible so that new users installing the operator from now on will get the fix directly.

> Releasing the new version(5.13) is not possible for us now because we have a public roadmap that has already been announced to our customers. It will create huge confusion on their side.

Can't you issue a new z release, like 5.12.1?

> I could see some revert PRs which were created after the announcement: #4221

That specific example (and I'm sure this applies to any other revert pr you can find since the switch to the new CI) was a revert of a change that did not end up being published to any operator index: that's something we can do if we can catch the issue before the release pipeline completes successfully, but unfortunately it's not the case for your request.

> Could you make an exception for us just for once? We have already started to change our release script to make it compatible with your policy.

What you are asking for is not just a revert of a commit in a git repo: your previous PR was already processed by the release pipeline which updated the operator index of each supported openshift version to include the 5.12.0 bundle (that's what the `operator-release-pipeline/passed` label in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4442 means).
Undoing that would require manually altering 5 different operator indices, one for each supported openshift version, which is a slow, complex and very error prone operation when done manually.

**Comment by hasancelik** [comment]
@mporrato 

Thanks for your detailed answers.

>Can't you issue a new z release, like 5.12.1?

it will be messy on our side.

> That specific example (and I'm sure this applies to any other revert pr you can find since the switch to the new CI) was a revert of a change that did not end up being published to any operator index: that's something we can do if we can catch the issue before the release pipeline completes successfully, but unfortunately it's not the case for your request.

> What you are asking for is not just a revert of a commit in a git repo: your previous PR was already processed by the release pipeline which updated the operator index of each supported openshift version to include the 5.12.0 bundle (that's what the operator-release-pipeline/passed label in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4442 means).
Undoing that would require manually altering 5 different operator indices, one for each supported openshift version, which is a slow, complex and very error prone operation when done manually.

I see, thanks for the explanation. 

I know updates are not allowed due to the policy, but our issue is at the docker image level, so can we update `clusterserviceversion.yaml` of 5.12 with new image details?
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4442/files#diff-2915a0425309d62c715cb47f0f91fd10f448c872f442c50230920c93a1f0c69bR254-R256

**Comment by hasancelik** [comment]
@mporrato

Thanks to @jfrancin, the certified counterpart of this PR has been reverted, FYI.
https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3843#issuecomment-2093377079

For the 'do-over' of the 5.12.0 release, we are waiting for your decision.

**Pull request closed without merging**
