### PR TITLE
operator korrel8r (0.0.8)

### PR DESCRIPTION
**Pull request by alanconway**
Request to create korrel8r operator

### CODE REVIEW

**Comment by alanconway** [comment]
The docs still refer to semver-skippatch here: https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md?plain=1#L179

**Review by Allda — APPROVED** [review]

**Comment by Allda** [comment]
> The docs refer to semver-skippatch here: https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md?plain=1#L185 - seems to be incorrect according to error above.

Good point! I already raised a PR with the removal https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4072

**Comment by alanconway** [comment]
Many thanks @Allda for your swift attention, I'm delighted to say I can now install Korrel8r via. OperatorHub.
I was impressesed by your onboarding process; all my effort went into improving my operator based on your check-lists and tests. When I did submit the PR there were couple of minor mistakes (which I immediately found were due to me not following clear instructions) and it Just Worked!!! Congrats to you and your team.

**Comment by alanconway** [comment]
@Allda the operator is visible and installable in the openshift console, but does not seem to be listed on operatorhub.io. Do I need to take additional steps, or is this just a periodic update that hasn't run yet?

**Pull request merged**
