### PR TITLE
Delete operators/hazelcast-platform-operator

### PR DESCRIPTION
**Pull request by devOpsHelm**
New Hazelcast Platform Operator will be published on certified-operators and community-operators-prod is no longer maintained.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-via-pr.md)?
* [ ] Are you familiar with our [operator pipeline](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/community-operator-pipeline.md)?
* [ ] Have you tested your Operator with all Custom Resource Definitions [packaging](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md)?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/operator-ci-yaml.md##Operator-versioning)?
* [ ] Have you considered whether you want to use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#operator-icon) set?

### Your submission should not

* [ ] Add more than one operator bundle per PR
* [ ] Modify any operator
* [ ] Rename an operator
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [ ] Description of the managed Application and where to find more information
2. [ ] Features and capabilities of your Operator and how to use it
3. [ ] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [ ] Human readable name and 1-liner description about your Operator
* [ ] Valid [category name](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md#categories)<sup>1</sup>
* [ ] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [ ] Links to the maintainer, source code and documentation
* [ ] Example templates for all Custom Resource Definitions intended to be used
* [ ] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by devOpsHelm** [comment]
Hello, @mvala @J0zi @mporrato @Allda 
Please take a look on this PR and merge it. 
New Hazelcast Platform Operator will be published on certified-operators and community-operators-prod is no longer maintained.

**Comment by mporrato** [comment]
As per https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/3679 , removal and modification of existing bundles is no longer supported by the community pipeline.

**Comment by hasancelik** [comment]
@mporrato, I acknowledge the policy, but we don't just want to remove one bundle version; we want to remove the entire listing. We won't be releasing a new version of this bundle, as mentioned earlier. We don't want to list the unsupported version of our bundle on the OCP OperatorHub dashboard. How can we achieve this?

**Comment by mporrato** [comment]
That involves removing the existing bundles too, which is not supported.

**Comment by hasancelik** [comment]
```
We don't want to list the unsupported version of our bundle on the OCP OperatorHub dashboard.
```
Do you have any solutions or advice for that? We do not want to list the old version of the bundle, which is not maintained by us anymore.

**Comment by Allda** [comment]
@hasancelik I did an initial step to convert the operator to FBC which will allow you to remove it. Here is a PR with draft changes. Please review it and approve if you agree with the changes. Once it is approved and merged you will be able to remove the operator.
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5035

**Comment by hasancelik** [comment]
@Allda We have already fully deprecated our operator with 5.13.1 release:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4904

To clarify, from what I understand, will our bundles be completely removed from the operatorhub dashboard with your PR (https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5035)?

**Comment by Allda** [comment]
> @Allda We have already fully deprecated our operator with 5.13.1 release: #4904
> 
> To clarify, from what I understand, will our bundles be completely removed from the operatorhub dashboard with your PR (#5035)?

Yes, you will be able to remove it completely from all places. Once my PR is merged you can then remove a whole content from the repository without failing a pipeline. This step will remove it from the git repo and operator hub.

**Comment by cheels** [comment]
Hello @Allda I just noticed that you forgot to add **5.13.0** and **5.13.1** versions to remove. Could you please add these 2 versions: 
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/hazelcast-platform-operator/5.13.0
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/hazelcast-platform-operator/5.13.1

We added 5.13.1 as a patch to notify customers that it was deprecated but since you are introduce the removal action we cat remove it completely. 

Thanks!

**Comment by Allda** [comment]
@cheels If you want an operator to be removed you need to first approve a conversion to a FBC. You can do it by giving me :+1: to this PR. https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5035

**Comment by Allda** [comment]
Closing the stale PR. If you want to continue and migrate to FBC feel free to reopen.

**Comment by cheels** [comment]
@Allda Why you closed this ticket? I put 👍 to this PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5035 as you asked.

**Pull request closed without merging**
