### PR TITLE
operators [R] [CI] prometheus (0.14.0 0.15.0 0.22.2 0.27.0 0.32.0 0.37.0 0.47.0 0.56.3)

### PR DESCRIPTION
**Pull request by ctrought**
Signed-off-by: ctrought <65360454+ctrought@users.noreply.github.com>

Thanks submitting your Operator. Please check below list before you create your Pull Request.

### New Submissions

* [ ] Are you familiar with our [contribution guidelines](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-via-pr.md)?
* [ ] Have you [packaged and deployed](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) your Operator for Operator Framework?
* [ ] Have you tested your Operator with all Custom Resource Definitions?
* [ ] Have you tested your Operator in all supported [installation modes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata)?
* [ ] Have you considered whether you want use [semantic versioning order](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md#semver-mode)?
* [ ] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?
* [ ] Is operator [icon](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#operator-icon) set?

### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [x] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [x] Modify more than one operator
* [ ] Modify an Operator you don't own
* [x] Rename an operator - please remove and add with a different name instead
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by ctrought** [comment]
@J0zi if I understand correctly, since this operator is bundled in packagemanifest format it needs to have `ci.yaml` updated to set [packagemanifestClusterVersionLabel](https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-ci-yaml/#:~:text=updateGraph%3A%20replaces%2Dmode-,Automatic%20Cluster%20Version%20Label%20(OCP)%20%2D%20packagemanifest%20only,-Starting%20OCP%20v4.9) to `auto`

However `ci.yaml` can only be modified separately by single file modify PR as per [the docs](https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-version-update/#:~:text=annotations.alm%2Dexamples-,Operator%20versioning%20strategy,-Warning), so I'll first have to create a separate PR to add that option?

**Comment by mvalarh** [comment]
@ctrought you can modify `ci.yaml` file in this PR

**Comment by ctrought** [comment]
> @ctrought you can modify `ci.yaml` file in this PR

Thanks, done. Any thoughts on the below, I'm seeing an additional entry for a previous version in the index causing tests to fail. The erroneous entry is matching the name of the csv as opposed to version/tag. I'll add I did slightly change the name of the current/new csv to follow recommendations from `opm` tests but I don't expect that would have had any effect.

image

image

```
$ find . -name *clusterserviceversion* | xargs grep -i replaces
./0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml:  replaces: prometheusoperator.0.15.0
./0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml:  replaces: prometheusoperator.0.14.0
./0.27.0/prometheusoperator.0.27.0.clusterserviceversion.yaml:  replaces: prometheusoperator.0.22.2
./0.37.0/prometheusoperator.0.37.0.clusterserviceversion.yaml:  replaces: prometheusoperator.0.32.0
./0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml:  replaces: prometheusoperator.0.37.0
./0.32.0/prometheusoperator.0.32.0.clusterserviceversion.yaml:  replaces: prometheusoperator.0.27.0
./0.56.2/prometheusoperator.0.56.2.clusterserviceversion.yaml:  replaces: prometheusoperator.0.47.0
```

**Comment by J0zi** [comment]
@ctrought please use the same name for every operator version. Also decide if you want to use `v` in version or not and use it it consistently across all versions. Inconsistent naming is breaking our pipeline:)

**Comment by mvalarh** [comment]
@ctrought if you want to use format for name like this `prometheus-operator.v0.56.2` . You can also change it in all versions and we will recreate whole operator

**Comment by ctrought** [comment]
Installs successfully on my 4.8 cluster.

**Comment by ctrought** [comment]
@J0zi @mvalarh are CI tests for 4.6 - 4.8 functional?

**Comment by J0zi** [comment]
@ctrought pipeline is unable to run the operator on clusters 4.6-4.8. I tried it myself on 4.6 and it is failing, see:
```
operator-sdk-1.21 run bundle quay.io/operator_testing/prometheus:edc8ec55
INFO[0021] Successfully created registry pod: quay-io-operator-testing-prometheus-edc8ec55 
INFO[0022] Created CatalogSource: prometheus-catalog    
INFO[0023] OperatorGroup "operator-sdk-og" created      
INFO[0023] Created Subscription: prometheusoperator-0-56-2-sub 
INFO[0026] Approved InstallPlan install-kxmnk for the Subscription: prometheusoperator-0-56-2-sub 
INFO[0026] Waiting for ClusterServiceVersion "default/prometheusoperator.0.56.2" to reach 'Succeeded' phase 
INFO[0026]   Waiting for ClusterServiceVersion "default/prometheusoperator.0.56.2" to appear 
FATA[0121] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition
```
Are you able to run it on 4.6? How do you do it?
If you restart prow by `/test all`, in about an hour you will have `quay.io/operator_testing/prometheus:edc8ec55` ready. Where `edc8ec55` is your latest commit. Image will be available for 15 hours.

Consider converting to [bundle format](https://redhat-openshift-ecosystem.github.io/community-operators-prod/packaging-operator/) and releasing for 4.9+ by [label](https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-ci-yaml/#automatic-cluster-version-label-ocp-packagemanifest-only) setting to `com.redhat.openshift.versions: "v4.9"`

**Comment by ctrought** [comment]
> @ctrought pipeline is unable to run the operator on clusters 4.6-4.8. I tried it myself on 4.6 and it is failing, see:
> 
> ```
> operator-sdk-1.21 run bundle quay.io/operator_testing/prometheus:edc8ec55
> INFO[0021] Successfully created registry pod: quay-io-operator-testing-prometheus-edc8ec55 
> INFO[0022] Created CatalogSource: prometheus-catalog    
> INFO[0023] OperatorGroup "operator-sdk-og" created      
> INFO[0023] Created Subscription: prometheusoperator-0-56-2-sub 
> INFO[0026] Approved InstallPlan install-kxmnk for the Subscription: prometheusoperator-0-56-2-sub 
> INFO[0026] Waiting for ClusterServiceVersion "default/prometheusoperator.0.56.2" to reach 'Succeeded' phase 
> INFO[0026]   Waiting for ClusterServiceVersion "default/prometheusoperator.0.56.2" to appear 
> FATA[0121] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition
> ```
> 
> Are you able to run it on 4.6? How do you do it? If you restart prow by `/test all`, in about an hour you will have `quay.io/operator_testing/prometheus:edc8ec55` ready. Where `edc8ec55` is your latest commit. Image will be available for 15 hours.
> 
> Consider converting to [bundle format](https://redhat-openshift-ecosystem.github.io/community-operators-prod/packaging-operator/) and releasing for 4.9+ by [label](https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-ci-yaml/#automatic-cluster-version-label-ocp-packagemanifest-only) setting to `com.redhat.openshift.versions: "v4.9"`

I built the catalog image using the (legacy?) method for packagemanifest [seen here](https://redhat-openshift-ecosystem.github.io/community-operators-prod/testing-operators/#publishing-your-operator-metadata-to-a-catalog-for-testing) and then created a CatalogSource using it and installed from the integrated OH. I wasn't using `operator-sdk run bundle` at the time so I guess there could be some differences in the two. However I've now converted to bundle format since it seems to be the path forward as you suggested, I've done for all previous releases as well since both types cannot be shipped together and also labelled for OCP releases.

**Pull request merged**
