### PR TITLE
operator opentelemetry-operator (0.92.0)

### PR DESCRIPTION
**Pull request by opentelemetrybot**
Release opentelemetry-operator `0.92.0`.

cc @pavolloffay @frzifus @yuriolisa @jaronoff97 @VineethReddy02 @TylerHelmuth @swiatekm-sumo

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Review by swiatekm-sumo — APPROVED** [review]

**Review by yuriolisa — APPROVED** [review]

**Review by iblancasa — APPROVED** [review]

**Review by jaronoff97 — APPROVED** [review]

**Review by frzifus — APPROVED** [review]

**Comment by iblancasa** [comment]
We need to push this manually because of the missing annotation https://github.com/open-telemetry/opentelemetry-operator/pull/2562

**Review by jaronoff97 — APPROVED** [review]

**Comment by Allda** [comment]
The bundle is missing `com.redhat.openshift.versions` annotation. Please add the missing annotation to pass the test and release the bundle.

**Pull request closed without merging**
