### PR TITLE
operator project-quay (3.8.1)

### PR DESCRIPTION
**Pull request by quay-devel**
Add 3.8.1 to community operators

### CODE REVIEW

**Comment by mvalarh** [comment]
@quay-devel can you look at logs: https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/3820763400/jobs/6502237228#step:6:1805

**Comment by J0zi** [comment]
@quay-devel, the pipeline is unable to parse CSV quay-operator.clusterserviceversion.yaml: error unmarshaling JSON: while decoding JSON: Numeric PreRelease version must not contain leading zeroes \"01\", no bundle csv found, unable to load bundle from directory 3.9.0-nightly.2023.01.09/manifests

It is not supported by `operator-sdk`, please use `3.9.0-nightly.20230109` for example.

**Comment by J0zi** [comment]
@quay-devel issue is that this is not a semver format.

**Pull request merged**
