### PR TITLE
operator eclipse-amlen-operator (1.0.2)

### PR DESCRIPTION
**Pull request by IanBoden**
Thanks for submitting your Operator. Please check the below list before you create your Pull Request.

### New Submissions

N/A

### Your submission should not

* [x] Add more than one operator bundle per PR
* [x] Modify any operator
* [x] Rename an operator
* [x] Modify any files outside the above mentioned folders
* [x] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description of the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](./packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

--

<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

<sup>2</sup> For more information see [here](https://sdk.operatorframework.io/docs/overview/#operator-capability-level)

### CODE REVIEW

**Comment by Allda** [comment]
@IanBoden Your operator is missing the required field (`metadata.annotations.support`) as stated in the result of static checks. Please add the required fields based on the guide: https://redhat-openshift-ecosystem.github.io/community-operators-prod/packaging-required-fields/

**Comment by IanBoden** [comment]
@Allda thanks, have added the field and created a new PR #4347

The automated message saying:

> Author of the PR is not listed as one of the reviewers in ci.yaml.
> Please review the PR and approve it with /lgtm comment.
> 
> @IanBoden @jonquark
>
> Consider adding author of the PR to the ci.yaml file if you want automated approval for a followup submissions.

Is a little confusing, if I'm not a reviewer then how would I add myself as a reviewer? Is it a case issue, in the ci.yaml it lists ianboden but maybe it should be IanBoden? Though If it can get it for the automated message something seems dodgy.

**Pull request closed without merging**
