### PR TITLE
operators special-resource-operator (4.8.0)

### PR DESCRIPTION
**Pull request by dagrayvid**
Signed-off-by: David Gray <dagray@redhat.com>
### Updates to existing Operators

* [x] Did you create a `ci.yaml` file according to the [update instructions](https://github.com/operator-framework/community-operators/blob/master/docs/operator-ci-yaml.md)?
* [x] Is your new CSV pointing to the previous version with the `replaces` property if you chose `replaces-mode` via the `updateGraph` property in `ci.yaml`?
* [x] Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
* [ ] Have you tested an update to your Operator when deployed via OLM?
* [x] Is your submission [signed](https://github.com/operator-framework/community-operators/blob/master/docs/contributing-prerequisites.md#sign-your-work)?

### Your submission should not

* [ ] Modify more than one operator
* [ ] Modify an Operator you don't own
* [ ] Rename an operator - please remove and add with a different name instead
* [ ] Submit operators to both `upstream-community-operators` and `community-operators` at once
* [ ] Modify any files outside the above mentioned folders
* [ ] Contain more than one commit. **Please squash your commits.**

### Operator Description must contain (in order)

1. [x] Description about the managed Application and where to find more information
2. [x] Features and capabilities of your Operator and how to use it
3. [x] Any manual steps about potential pre-requisites for using your Operator

### Operator Metadata should contain

* [x] Human readable name and 1-liner description about your Operator
* [x] Valid [category name](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#categories)<sup>1</sup>
* [x] One of the pre-defined [capability levels](https://github.com/operator-framework/operator-courier/blob/4d1a25d2c8d52f7de6297ec18d8afd6521236aa2/operatorcourier/validate.py#L556)<sup>2</sup>
* [x] Links to the maintainer, source code and documentation
* [x] Example templates for all Custom Resource Definitions intended to be used
* [x] A quadratic logo

Remember that you can preview your CSV [here](https://operatorhub.io/preview).

### CODE REVIEW

**Comment by dagrayvid** [comment]
@J0zi, as I recall from past updates to SRO, these deployment tests don't work because of the dependency on the node-feature-discovery operator. Is that still the case? Please let me know how to proceed.

**Comment by J0zi** [comment]
@dagrayvid, this is OK. Thank you for letting us know. I already opened a task for it.
But there is another failure which we should investigate. Please check and we will check also https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/22/checks?check_run_id=3107970598#step:3:949

**Comment by dagrayvid** [comment]
@J0zi, I think I've fixed that previous error mentioned.

**Comment by J0zi** [comment]
@dagrayvid `Value of 'metadata.annotations.containerImage' not found, please check`

**Pull request merged**
